- name: Install and setup Bottles
  vars:
    app_id: com.usebottles.bottles
  block:
    - name: Install {{ app_id }} with flatpak
      community.general.flatpak:
        method: user
        state: present
        remote: flathub
        name:
          - "{{ app_id }}"
    - name: Configure {{ app_id }} flatpak overrides
      copy:
        dest: "{{ xdg_data_home }}/flatpak/overrides/{{ app_id }}"
        content: |
          [Context]
          filesystems=home
        mode: '0644'
        backup: false
