---
- name: Install and setup Kid3 (tag editor)
  when: [is_home]
  vars:
    app_id: org.kde.kid3
  block:
    - name: Install {{ app_id }} with flatpak
      community.general.flatpak:
        method: user
        state: present
        remote: flathub
        name: ['{{ app_id }}']
    - name: Configure {{ app_id }} flatpak overrides
      copy:
        dest: '{{ xdg_data_home }}/flatpak/overrides/{{ app_id }}'
        content: |
          [Context]
          filesystems=/media;home
        mode: '0644'
        backup: false
