# <https://flathub.org/apps/md.obsidian.Obsidian>
#
# LICENSE:
#   - <https://help.obsidian.md/teams/license>
#   - <https://obsidian.md/blog/free-for-work/?ref=creativerly.com>
- name: Install and setup Obsidian
  vars:
    app_id: md.obsidian.Obsidian
  block:
    - name: Install {{ app_id }} with flatpak
      community.general.flatpak:
        method: user
        state: present
        remote: flathub
        name:
          - "{{ app_id }}"
    - name: Configure {{ app_id }} flatpak overrides
      copy:
        dest: "{{ xdg_data_home }}/flatpak/overrides/{{ app_id }}"
        content: |
          [Context]
          sockets=wayland
        mode: '0644'
        backup: false
    - name: Create {{ app_id }} desktop entry
      copy:
        dest: "{{ xdg_data_home }}/applications/{{ app_id }}.desktop"
        content: |
          [Desktop Entry]
          Name=Obsidian
          Exec=flatpak run --branch=stable --command=obsidian.sh --file-forwarding md.obsidian.Obsidian --ozone-platform-hint=auto --enable-features=UseOzonePlatform --enable-wayland-ime --wayland-text-input-version=3 @@u %U @@
          Terminal=false
          Type=Application
          Icon=md.obsidian.Obsidian
          StartupWMClass=obsidian
          Comment=Obsidian
          MimeType=x-scheme-handler/obsidian;
          Categories=Office;
          X-Flatpak-Tags=proprietary;
          X-Flatpak=md.obsidian.Obsidian
        mode: '0600'
        backup: false
