- add video-zoom -0.076
1 set current-window-scale 0.5
2 set current-window-scale 1.0
3 set current-window-scale 2.0
= add video-zoom +0.076
DOWN seek -30 keyframes
END seek 60 keyframes
F cycle-values fullscreen yes no ; cycle-values panscan 1.0 0.0
F10 add video-pan-y -.05
F11 add video-pan-y .05
F12 add video-pan-x -.05
F5 add video-rotate -1
F6 set video-rotate 0
F7 add video-rotate 1
F9 add video-pan-x .05
HOME seek 60 keyframes
LEFT no-osd seek -1 keyframes
R cycle_values video-rotate 270 180 90 0
RIGHT no-osd seek +1 keyframes
UP seek 30 keyframes
WHEEL_DOWN seek -1 keyframes
WHEEL_UP seek +1 keyframes
X add sub-delay +0.1
b cycle deband
c add sub-delay +0.1
d cycle deinterlace
k vf toggle deblock
m cycle mute
r cycle_values video-rotate 90 180 270 0
x add sub-delay -0.1
