
ao=%8%pipewire
cdda-paranoia=%1%2
cdda-speed=%1%1
cscale=%20%ewa_lanczos4sharpest
deband=%3%yes
deband-iterations=%1%3
dscale=%17%ewa_robidouxsharp
dvd-speed=%1%1
geometry=%9%2720x1530
gpu-api=%6%vulkan
hwdec=%9%auto-copy
osd-bar=%2%no
osd-bar-outline-size=%1%1
osd-blur=%8%0.100000
osd-bold=%3%yes
osd-duration=%3%800
osd-font=%9%Monospace
osd-font-size=%2%35
osd-fractions=%3%yes
osd-level=%1%1
pipewire-volume-mode=%6%global
replaygain=%5%track
replaygain-fallback=%2%-6
scale=%20%ewa_lanczos4sharpest
screenshot-directory=%36%/home/hnjae/Pictures/mpv-screenshots
screenshot-format=%3%png
screenshot-high-bit-depth=%3%yes
screenshot-jpeg-quality=%2%95
screenshot-jxl-distance=%1%0
screenshot-jxl-effort=%1%9
screenshot-png-compression=%1%9
screenshot-tag-colorspace=%3%yes
screenshot-template=%12%%F-%P-(%t%F)
screenshot-webp-compression=%1%6
screenshot-webp-lossless=%3%yes
screenshot-webp-quality=%3%100
sigmoid-upscaling=%3%yes
sub-blur=%8%0.100000
sub-bold=%3%yes
sub-outline-size=%8%1.650000
sws-allow-zimg=%3%yes
sws-scaler=%6%spline
target-colorspace-hint=%3%yes
term-osd-bar=%3%yes
vd-lavc-framedrop=%6%nonref
vd-lavc-show-all=%3%yes
vd-lavc-skiploopfilter=%4%none
vo=%8%gpu-next
ytdl-format=%175%best*[vcodec!=none][height>=1080][height<=1440][fps<=60][acodec!=none]/best*[vcodec!=none][height>=1080][height<=1440][fps<=60][acodec=none]+bestaudio/bestvideo+bestaudio/best
zimg-fast=%2%no
zimg-scaler=%8%spline36
zimg-scaler-chroma=%8%spline36

[anime]
zimg-scaler=%7%lanczos

[audio]
replaygain=%5%track

[audio-normalize]
af=%8%loudnorm

[deblock]
hwdec=%9%auto-copy
scale-blur=%3%0.9
vf=%21%deblock=filter=strong

[deinterlace]
deinterlace=%2%no
hwdec=%9%auto-copy
vf=%5%bwdif

[deinterlace-slow]
deinterlace=%2%no
hwdec=%9%auto-copy
vf=%5%nnedi

[denoise]
hwdec=%9%auto-copy
vf=%6%hqdn3d

[denoise-slow]
hwdec=%9%auto-copy
vf=%4%bm3d

[hdr]
gpu-api=%6%vulkan
target-colorspace-hint=%3%yes
target-contrast=%4%auto
vo=%8%gpu-next

[medium]
cscale=%11%ewa_lanczos
dscale=%7%hermite
scale=%11%ewa_lanczos
sws-scaler=%7%bicubic
vd-lavc-skiploopfilter=%7%default
zimg-scaler=%8%spline16
zimg-scaler-chroma=%8%spline16

[sw-scale]
hwdec=%9%auto-copy
vf=%5%scale

[very-fast]
correct-downscaling=%2%no
cscale=%8%bilinear
deband=%2%no
deband-iterations=%1%1
dscale=%8%bilinear
hwdec=%4%auto
scale=%8%bilinear
sws-allow-zimg=%2%no
sws-fast=%3%yes
sws-scaler=%13%fast-bilinear
vd-lavc-skiploopfilter=%7%default
zimg-fast=%3%yes
zimg-scaler=%8%bilinear
zimg-scaler-chroma=%8%bilinear

