vo=gpu-next # use scale/cscale/dscale
gpu-api=vulkan
hwdec=vaapi # NOTE: auto uses vulkan <2026-04-03>
scale=ewa_lanczos4sharpest
sigmoid-upscaling=yes # Upscaling 시 halo 효과 제어
cscale=ewa_lanczos4sharpest # chroma upscale
dscale=ewa_robidouxsharp # downscale
opengl-pbo=yes

panscan=1
wayland-app-id=io.mpv.Mpv

target-colorspace-hint=auto
target-contrast=auto

vd-lavc-framedrop=nonref
vd-lavc-show-all=yes
vd-lavc-skiploopfilter=none

ao=pipewire
pipewire-volume-mode=global

cdda-paranoia=%1%2
cdda-speed=1
dvd-speed=1

deband=no
deband-iterations=3

replaygain=album
replaygain-fallback=-6
term-osd-bar=yes

ytdl-format=%175%best*[vcodec!=none][height>=1080][height<=1440][fps<=60][acodec!=none]/best*[vcodec!=none][height>=1080][height<=1440][fps<=60][acodec=none]+bestaudio/bestvideo+bestaudio/best

# Window Size
autofit-larger=78%x78%
autofit-smaller=60%x60%

# Sub
sub-blur=0.100000
sub-bold=yes
sub-outline-size=1.650000

# OSD
osd-bar=%2%no
osd-bar-outline-size=%1%1
osd-blur=%8%0.100000
osd-bold=%3%yes
osd-duration=%3%800
osd-font=%9%Monospace
osd-font-size=%2%35
osd-fractions=%3%yes
osd-level=%1%1

# Screenshot
screenshot-dir=~/Pictures/mpv-screenshots
screenshot-template=%12%%F-%P-(%t%F)
screenshot-format=png
screenshot-tag-colorspace=yes
screenshot-high-bit-depth=yes
screenshot-jpeg-quality=95
screenshot-jxl-distance=0 # lossless
screenshot-jxl-effort=1
screenshot-png-compression=1
screenshot-png-filter=0
screenshot-webp-compression=0
screenshot-webp-lossless=yes
screenshot-webp-quality=100

[sw-scale]
hwdec=auto-copy
vf=scale=w=1280:h=-2
sws-allow-zimg=yes
zimg-fast=no
zimg-scaler=lanczos
zimg-scaler-chroma=spline36
zimg-fast=yes
video-unscaled=yes
# zimg-scaler=spline36

[audio-normalize]
af=loudnorm

[deblock]
hwdec=auto-copy
scale-blur=0.9
vf=deblock=filter=strong

[deinterlace]
deinterlace=no
hwdec=auto-copy
vf=bwdif

[deinterlace-slow]
deinterlace=no
hwdec=auto-copy
vf=nnedi

[denoise]
hwdec=auto-copy
vf=hqdn3d

[denoise-slow]
hwdec=auto-copy
vf=bm3d

[very-fast]
scale=bilinear
correct-downscaling=no
cscale=bilinear
dscale=bilinear
deband=no
deband-iterations=1
hwdec=auto
sws-allow-zimg=no
sws-fast=yes
sws-scaler=fast-bilinear
vd-lavc-skiploopfilter=default
