xdg_open      = true
xdg_open_fork = true
use_trash     = true

# TODO: $HOME 에 relative 하게 설정할 수는 없나? <2025-07-06>
custom_commands = [
  # { name = "newfile", command = "~/.config/joshuto/bin/newfile '%text'" },
  { name = "newfile", command = "/home/hnjae/.config/joshuto/bin/newfile '%text'" },
  # { name = "rgfzf", command = "/home/hnjae/.config/joshuto/bin/rgfzf '%text' %s" },
  # { name = "rg", command = "/home/<USER>/.config/joshuto/rg '%text' %s" },
]


[display]
mode         = "default"
column_ratio = [1, 10, 7]
# mode              = "hsplit"
line_number_style = "relative"
show_borders      = false
show_hidden       = true

[preview]
max_preview_size = "128 MB"
use_xdg_thumbs   = true
xdg_thumb_size   = "xxlarge"
preview_script   = "~/.config/joshuto/bin/pistol-wrapper"
