- name: Setup Zotero with flatpak
  hosts: localhost
  become: false
  vars:
    app_id: org.zotero.Zotero
    xdg_data_home: "{{ ansible_env.XDG_DATA_HOME | default(ansible_env.HOME + '/.local/share') }}"
  tasks:
    - name: Install {{ app_id }} with flatpak
      community.general.flatpak:
        method: user
        state: present
        remote: flathub
        name:
          - "{{ app_id }}"
    - name: Configure {{ app_id }} flatpak overrides
      copy:
        dest: "{{ xdg_data_home }}/flatpak/overrides/{{ app_id }}"
        content: |
          [Context]
          filesystems=!home
        mode: '0644'
        backup: false
