- name: Add flathub repo
  include_tasks: add-flathub-repo.yaml
- name: Install bruno
  include_tasks: bruno.yaml
- name: Install gimp
  include_tasks: gimp.yaml
- name: Install home apps
  include_tasks: home-apps.yaml
- name: Install bottles
  include_tasks: home-bottles.yaml
- name: Install calibre
  include_tasks: home-calibre.yaml
- name: Install fooyin
  include_tasks: home-fooyin.yaml
- name: Install kid3
  include_tasks: home-kid3.yaml
- name: Install opera
  include_tasks: home-opera.yaml
- name: Install picard
  include_tasks: home-picard.yaml
- name: Install puddletag
  include_tasks: home-puddletag.yaml
- name: Install telegram
  include_tasks: home-telegram.yaml
- name: Install ticktick
  include_tasks: home-ticktick.yaml
- name: Install zotero
  include_tasks: home-zotero.yaml
- name: Install libreoffice
  include_tasks: libreoffice.yaml
- name: Install okular
  include_tasks: okular.yaml
- name: Install thunderbird
  include_tasks: thunderbird.yaml
- name: Install yacreader
  include_tasks: yacreader.yaml
- name: Install image viewer
  include_tasks: image-viewer.yaml
- name: Install various apps
  include_tasks: various-apps.yaml
- name: Remove deprecated apps
  include_tasks: remove-apps.yaml
- name: Apply global overrides
  include_tasks: global-overrides.yaml
