
# profile=gpu-hq
scale=spline36
# cscale=spline36 # 이거하면 아이유 VP9 4k 못돌림
cscale=bilinear
dscale=mitchell
dither-depth=auto
correct-downscaling=yes
linear-downscaling=yes
sigmoid-upscaling=yes
deband=yes

#
vo=gpu
gpu-api=opengl # vulkan 보다 낫다.
# gpu-api=vulkan

# Other
framedrop=vo
hr-seek=no # always use keyffames


# vf-defaults="vavpp=deint=motion-adaptive"
# vf="vavpp=deint=motion-adaptive"
# vf="format=fmt=monow"
# vf="format=colorlevel=full"
# Default
vd-lavc-threads="0" # auto; maximum 16
# hwdec=vaapi
# vd-lavc-o=deint=weave

# Scale # lanczos, sinc, bicublin ...
sws-scaler="spline"
# vf=scale=-3:2160

#vd-lavc-skiploopfilter="none"
# deinterlace="no"

# spirv-compiler=shaderc
keep-open =yes

###############################################################################
## Audio
###############################################################################
ao=pipewire
volume=100
volume-max=100
# softvol=no
replaygain=track # default: no
audio-channels="2"
# ad-lavc-downmix="yes"
ad-lavc-threads="0"
# audio-normalize-downmix="yes" # default: no


###############################################################################
## Window
###############################################################################
#title='${filename}'
# autofit-larger="40%"
keepaspect="yes"
#cursor-autohide-fs-only="yes"
# cache-secs=120
stop-screensaver="yes"

###############################################################################
# OSD Settings
###############################################################################
osd-level=1
osd-fractions=yes
# osd-font="Sans Serif"
osd-bar="no"
osd-duration="800" # default: 1000
osd-blur="0.2"     # default: 0
#input-default-bindings="no"

###############################################################################
# Subtitle Settings
###############################################################################

slang="ko,kor,en,eng"
sub-ass="no"
embeddedfonts="no"
sub-auto="exact"
sub-font="KoreanCNMM"
# sub-ass-styles="$HOME/.config/mpv/styles.ass"

#sub-font="Sub"
# sub-blur="0.2"
# sub-border-size="2.4"
sub-blur="0.16"
sub-border-size="2.7"
sub-scale="0.82"
#sub-scale="1.15"
sub-codepage="utf8:cp949"
sub-pos="96"
sub-gray="yes"

###############################################################################
# Screenshot
###############################################################################
screenshot-format="png"
screenshot-template="%F-%P"
screenshot-png-compression="9"

###############################################################################
# Profiles
###############################################################################
#[Japanese]

#[Denoise]
#vf=scale:-3:1080,hqdn3d:2:1:7:

#[Deinterace]
#deinterlace="yes"
#field-dominance="auto"

# [svp]
# input-ipc-server=/tmp/mpvsocket     # Receives input from SVP
# hr-seek-framedrop=no                # Fixes audio desync
# resume-playback=no                  # Not compatible with SVP
# vf=scale=-3:2160
[output-image]
vo=image
vo-image-format=png
# vo-image-compression=0


# [4k]
# profile-desc=cond:get('width', -math.huge) >= 3840
[wayland]
vo=wlshm
sws-scaler=fast-bilinear

[60FPS]
# profile-desc=cond:is_laptop() and get('container-fps', 0) >= 59
profile-desc=cond:is_laptop() and get('container-fps', 0) >= 59
scale=bilinear
cscale=bilinear

[svp]
input-ipc-server=/tmp/mpvsocket     # Receives input from SVP
hr-seek-framedrop=no                # Fixes audio desync
resume-playback=no                  # Not compatible with SVP
hwdec=nvdec-copy

# Can fix stuttering in some cases, in other cases probably causes it. Try it if you experience stuttering.
#opengl-early-flush=yes
