# NOTE:
#   - following version 0.1.3 of base24 <2026-03-15>
#   - <https://github.com/tinted-theming/base24/blob/main/styling.md>
#
# Base24 my-code-dark - alacritty color config
# Scheme by Original by tomasiser (https://github.com/tomasiser/vim-code-dark), Ported by hnjae (https://github.com/hnjae)

# COLORFGBG = if (config.base-home.base24.variant == "light") then "0;15" else "15;0";
# [env]
# COLORFGBG = "${COLORFGBG}"

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1e1e1e'
foreground = '0xd4d4d4'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1e1e1e'
cursor = '0xd4d4d4'

[colors.normal]
black = '0x1e1e1e'
red = '0xd16969'
green = '0x608b4e'
yellow = '0xd7ba7d'
blue = '0x569cd6'
magenta = '0xc586c0'
cyan = '0x9cdcfe'
white = '0xd4d4d4'

# Bright colors
[colors.bright]
black = '0x808080'
red = '0xd16969'
green = '0x608b4e'
yellow = '0xd7ba7d'
blue = '0x569cd6'
magenta = '0xc586c0'
cyan = '0x9cdcfe'
white = '0xffffff'

[[colors.indexed_colors]]
index = 16
color = "0xb5cea8"

[[colors.indexed_colors]]
index = 17
color = "0xce9178"

[[colors.indexed_colors]]
index = 18
color = "0x262626"

[[colors.indexed_colors]]
index = 19
color = "0x808080"

[[colors.indexed_colors]]
index = 20
color = "0x808080"

[[colors.indexed_colors]]
index = 21
color = "0xe9e9e9"

# vi:ft=toml
