---
- name: Reload systemd user daemon (`systemd --user daemon-reload`)
  listen: reload-systemd-user-daemon
  when: ansible_service_mgr == "systemd"
  systemd:
    daemon_reload: true
    scope: user
