#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import re
import time
from typing import Any, List

from loguru import logger
from i3ipc import Connection, Event

_BROSER_POPUP_PATTERNS: List = [
    # 알라딘
    re.compile(r"\[알라딘\] .*"),
    re.compile(r"마일리지를 적립금으로 전환 .*"),
    re.compile(r"알라딘 .*"),
    # 네이버
    re.compile(r"네이버페이 .*"),
    # Payco
    re.compile(r"로그인 .*"),
    re.compile(r"PAYCO .*"),
    # 인터파크
    re.compile(r"구매확정 팝업 .*"),
    # auction
    re.compile(r"옥션 - 로그인 .*"),
    # lotte card from market
    re.compile(r"롯데카드 통합 일반/간편서비스 .*"),
    # address
    re.compile(r"Daum Postcode Service .*"),
    # 신용카드인증
    re.compile(r"라온시큐어 카드본인확인서비스 .*"),
]

PATTERNS = {
    # value: (Should_wait, patterns)
    "firefox": (True, _BROSER_POPUP_PATTERNS),
    "chromium": (True, _BROSER_POPUP_PATTERNS),
}
PATTERNS_KEYS = PATTERNS.keys()


def on_window_new(i3, e: Any):

    if e.container.app_id not in PATTERNS_KEYS:
        return

    logger.info(
        f"({e.container.id}) new pop-up may need window event: "
        f"[{e.container.app_id}({e.container.name})]"
    )

    if PATTERNS[e.container.app_id][0]:
        logger.info(
            f"({e.container.id}) waiting window to load its contents"
        )
        time.sleep(0.8)

    con: Any | None = i3.get_tree().find_by_id(e.container.id)

    if con is None:
        logger.info(f"({e.container.id}) window closed")
        return
    if not con.focused:
        logger.info(f"({e.container.id}) window is not focused")
        return
    if not isinstance(con.name, str) or len(con.name) == 0:
        # logger.info(f"({e.container.id}) window is not focused")
        return

    for pattern in PATTERNS[e.container.app_id][1]:
        if not pattern.fullmatch(con.name):
            continue
        logger.info(
            f"({e.container.id}) floating window: {con.name}"
        )
        i3.command(f"[con_id={con.id}] floating enable")
        return
    return


if __name__ == "__main__":
    i3: Connection = Connection()
    i3.on(Event.WINDOW_NEW, on_window_new)
    i3.main()
