#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import asyncio
import re
import time
from typing import Any, List

from i3ipc import Event
from i3ipc.aio import Connection
from loguru import logger

_BROSER_POPUP_PATTERNS: List = [
    # 알라딘
    re.compile(r"\[알라딘\] .*"),
    re.compile(r"마일리지를 적립금으로 전환 .*"),
    re.compile(r"알라딘 .*"),
    # 네이버
    re.compile(r"네이버페이 .*"),
    # Payco
    re.compile(r"로그인 .*"),
    re.compile(r"PAYCO .*"),
    # 인터파크
    re.compile(r"구매확정 팝업 .*"),
    # auction
    re.compile(r"옥션 - 로그인 .*"),
    # lotte card from market
    re.compile(r"롯데카드 통합 일반/간편서비스 .*"),
]

PATTERNS = {
    # value: (Should_wait, patterns)
    "firefox": (True, _BROSER_POPUP_PATTERNS),
    "chromium": (True, _BROSER_POPUP_PATTERNS),
}
PATTERNS_KEYS = PATTERNS.keys()


async def on_window_new(i3, e: Any):

    if e.container.app_id not in PATTERNS_KEYS:
        return

    logger.info(
        "new window event: "
        f"{e.container.id}[{e.container.app_id}({e.container.name})]"
    )

    if PATTERNS[e.container.app_id][0]:
        logger.info(f"detected browser: waiting browser to load page")
        time.sleep(0.8)

    con: Any | None = await i3.get_tree().find_by_id(e.container.id)

    if con is None:
        return
    if not con.focused:
        return
    if not isinstance(con.name, str) or len(con.name) == 0:
        return

    for pattern in PATTERNS[e.container.app_id][1]:
        if not pattern.fullmatch(con.name):
            continue
        logger.info(
            f"container {con.id}[{con.app_id}({con.name})] floating enable"
        )
        await i3.command(f"[con_id={con.id}] floating enable")
        return
    return


async def main():
    # i3: Connection = await Connection()
    i3: Connection = await Connection(auto_reconnect=True).connect()
    i3.on(Event.WINDOW_NEW, on_window_new)
    await i3.main()

if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())
