#!/usr/bin/env -S just --justfile

set fallback := true

_:
    @just --list

upgrade:
    ya pkg upgrade

[group('ci')]
selene:
    git ls-files -z -- '*.lua' | xargs -0 -r selene

[group('ci')]
check: selene
    ruff check
    ty check
    typos
