[[mgr.prepend_keymap]]
on = ["d"]
run = "create --dir"
desc = "Create a directory"

[[mgr.prepend_keymap]]
on = ["%"]
run = "plugin my-file-create"
desc = "Create a file"

[[mgr.prepend_keymap]]
on = ["D"]
run = "remove"
desc = "Trash selected files"

[[mgr.prepend_keymap]]
on = ["x"]
run = "plugin my-open-associated"
desc = "Open hovered entry with associated program"

[[mgr.prepend_keymap]]
on = ["p"]
run = "spot"
desc = "Spot hovered file"

[[mgr.prepend_keymap]]
on = ["P"]
run = "spot"
desc = "Spot hovered file"

[[mgr.prepend_keymap]]
on = ["g", "p"]
run = "paste"
desc = "Paste yanked files"

[[mgr.prepend_keymap]]
on = ["g", "P"]
run = "paste --force"
desc = "Paste yanked files (overwrite if the destination exists)"

[[mgr.prepend_keymap]]
on = ["1"]
run = "plugin relative-motions 1"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["2"]
run = "plugin relative-motions 2"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["3"]
run = "plugin relative-motions 3"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["4"]
run = "plugin relative-motions 4"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["5"]
run = "plugin relative-motions 5"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["6"]
run = "plugin relative-motions 6"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["7"]
run = "plugin relative-motions 7"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["8"]
run = "plugin relative-motions 8"
desc = "Move in relative steps"

[[mgr.prepend_keymap]]
on = ["9"]
run = "plugin relative-motions 9"
desc = "Move in relative steps"
