# Regroup this file with `python3 lib/generate-keymap.py` after edits.

[mgr]
prepend_keymap = [
  # Disabled Defaults
  { on = ["c", "c"], run = "noop" },
  { on = ["m", "s"], run = "noop" },
  { on = ["m", "b"], run = "noop" },
  { on = ["m", "o"], run = "noop" },
  { on = ["m", "n"], run = "noop" },
  { on = ["m", "m"], run = "noop" },

  # Quit
  { on = ["q", "q"], run = "quit", desc = "Quit the process" },

  # Files
  { on = ["d"], run = "create --dir", desc = "Create a directory" },
  { on = ["%"], run = "plugin my-file-create", desc = "Create a file" },
  { on = ["D"], run = "remove", desc = "Trash selected files" },
  { on = ["<F8>"], run = "plugin my-rmdir", desc = "Remove empty directories" },
  { on = ["<F3>"], run = "plugin my-trash-with-trace", desc = "Trash hovered file and create a trace file" },
  { on = ["a"], run = "rename --hovered --cursor=before_ext", desc = "Rename hovered file before extension" },
  { on = ["A"], run = "rename --hovered --cursor=end", desc = "Rename hovered file at end" },
  { on = ["R"], run = "plugin my-rename-with-vimv", desc = "Rename with vimv" },

  # Sorting
  { on = ["r"], run = "plugin my-toggle-sort-reverse", desc = "Toggle reverse sort" },
  { on = ["s"], run = "plugin my-select-sort", desc = "Select sort mode" },

  # Navigation
  { on = ["q", "f"], run = "spot", desc = "Spot hovered file" },
  { on = ["g", "s"], run = "plugin zoxide", desc = "zoxide" },
  { on = ["g", "t"], run = "plugin fzf", desc = "fzf" },
  { on = ["g", "h"], run = "hidden toggle", desc = "Toggle dotfiles" },
  { on = ["g", "o"], run = "plugin my-open-in-split down", desc = "Open hovered entry in horizontal split" },
  { on = ["g", "p"], run = "plugin my-change-permissions", desc = "Change hovered entry permissions" },
  { on = ["g", "v"], run = "plugin my-open-in-split right", desc = "Open hovered entry in vertical split" },
  { on = ["u"], run = "back", desc = "Back to previous directory" },
  { on = ["U"], run = "forward", desc = "Forward to next directory" },
  { on = ["-"], run = "leave", desc = "Go to the parent directory" },
  { on = ["x"], run = "plugin my-open-associated", desc = "Open hovered entry with associated program" },
  { on = ["p"], run = "spot", desc = "Spot hovered file" },
  { on = ["P"], run = "spot", desc = "Spot hovered file" },
  { on = ["<Enter>"], run = "plugin my-open-netrw-cr", desc = "Enter directory or open hovered file" },

  # Clipboard
  { on = ["m", "a"], run = "toggle_all --state=on", desc = "Select all files" },
  { on = ["m", "A"], run = "toggle_all --state=off", desc = "Deselect all files in current directory" },
  { on = ["m", "r"], run = "toggle_all", desc = "Reverse selection in current directory" },
  { on = ["m", "f"], run = "toggle", desc = "Toggle hovered file selection" },
  { on = ["m", "p"], run = "paste", desc = "Paste" },
  { on = ["m", "P"], run = "paste --force", desc = "Paste (overwrite)" },
  { on = ["m", "u"], run = "escape --select", desc = "Clear all selected files" },
  { on = ["m", "c"], run = "yank", desc = "Copy" },
  { on = ["m", "m"], run = "yank --cut", desc = "Cut" },
  { on = ["m", "F"], run = "unyank", desc = "Cancel the yank status" },

  # System clipboard
  { on = ["y", "y"], run = "plugin my-copy-file-clipboard", desc = "Copy hovered or selected entries to desktop clipboard" },
  { on = ["y", "c"], run = "plugin my-copy-file-content", desc = "Copy hovered file contents to desktop clipboard" },
  { on = ["y", "r"], run = "plugin my-copy-bracket-content round-first", desc = "Copy first () content from filename" },
  { on = ["y", "R"], run = "plugin my-copy-bracket-content round-last", desc = "Copy last () content from filename" },
  { on = ["y", "b"], run = "plugin my-copy-bracket-content square-first", desc = "Copy [] content from filename" },
  { on = ["y", "B"], run = "plugin my-copy-bracket-content square-last", desc = "Copy last [] content from filename" },
  { on = ["y", "("], run = "plugin my-copy-bracket-content round-first", desc = "Copy first () content from filename" },
  { on = ["y", ")"], run = "plugin my-copy-bracket-content round-last", desc = "Copy last () content from filename" },
  { on = ["y", "["], run = "plugin my-copy-bracket-content square-first", desc = "Copy [] content from filename" },
  { on = ["y", "]"], run = "plugin my-copy-bracket-content square-last", desc = "Copy last [] content from filename" },
  { on = ["y", "p"], run = "copy path", desc = "Copy the file path" },

  # Linemode
  { on = ["i", "s"], run = "linemode size", desc = "Linemode: size" },
  { on = ["i", "i"], run = "linemode none", desc = "Reset" },
  { on = ["i", "p"], run = "linemode permissions", desc = "Linemode: permissions" },
  { on = ["i", "b"], run = "linemode btime", desc = "Linemode: btime" },
  { on = ["i", "m"], run = "linemode mtime", desc = "Linemode: mtime" },
  { on = ["i", "o"], run = "linemode owner", desc = "Linemode: owner" },
  { on = ["i", "n"], run = "linemode none", desc = "Linemode: none" },

  # Relative Motions
  { on = ["1"], run = "plugin relative-motions 1", desc = "Move in relative steps" },
  { on = ["2"], run = "plugin relative-motions 2", desc = "Move in relative steps" },
  { on = ["3"], run = "plugin relative-motions 3", desc = "Move in relative steps" },
  { on = ["4"], run = "plugin relative-motions 4", desc = "Move in relative steps" },
  { on = ["5"], run = "plugin relative-motions 5", desc = "Move in relative steps" },
  { on = ["6"], run = "plugin relative-motions 6", desc = "Move in relative steps" },
  { on = ["7"], run = "plugin relative-motions 7", desc = "Move in relative steps" },
  { on = ["8"], run = "plugin relative-motions 8", desc = "Move in relative steps" },
  { on = ["9"], run = "plugin relative-motions 9", desc = "Move in relative steps" },
]
