[preview]
image_quality = 80

[open]
prepend_rules = [
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = ["open", "reveal"] },
  { mime = "application/{xml,yaml,x-yaml}", use = ["edit", "reveal"] },
]

[plugin]
prepend_previewers = [
  # Allmytoes doesn't handle these by default
  { mime = "image/svg+xml", run = "magick" },
  { mime = "image/heic", run = "magick" },
  { mime = "image/jxl", run = "magick" },
  # Handle other image types with allmytoes
  { mime = "image/*", run = "allmytoes" },
]

prepend_preloaders = [
  # Allmytoes doesn't handle these by default
  { mime = "image/svg+xml", run = "magick" },
  { mime = "image/heic", run = "magick" },
  { mime = "image/jxl", run = "magick" },
  # Handle other image types with allmytoes
  { mime = "image/*", run = "allmytoes" },
  # { url = '*.cb{z,r}', run = 'preview-cbz' },
  # { url = '*.cb{z,r}', run = 'preview-cbz' },
  { name = "*.{hwp,hwpx}", run = "hwp-preview" },
  { name = "*.{hwp,hwpx}", run = "hwp-preview" },
]

prepend_spotters = [
  { mime = "image/*", run = "spot-image" },
  { url = '*.cb{z,r}', run = 'spot-cbz' },
  { url = "video/*", run = "spot-video" },
]
