# term=foot-extra
font=Monospace:size=12

# scheme: "codedark"
# author: "Tomas Iser (https://github.com/tomasiser)"

[cursor]
color=1e1e1e d4d4d4

[colors]
foreground=d4d4d4
background=1e1e1e
regular0=1e1e1e
regular1=d16969
regular2=608b4e
regular3=d7ba7d
regular4=569cd6
regular5=c586c0
regular6=9cdcfe
regular7=d4d4d4
bright0=3c3c3c
bright1=d16969
bright2=608b4e
bright3=d7ba7d
bright4=569cd6
bright5=c586c0
bright6=9cdcfe
bright7=ffffff
