---
- name: Check if flatpak exists in PATH
  command: which flatpak
  register: flatpak_check
  failed_when: false
  changed_when: false
- name: Deploy flatpak update service & timer
  when: [flatpak_check.rc == 0]
  vars:
    service_name: flatpak-update
    flatpak_bin: '{{ flatpak_check.stdout }}'
    description: Update flatpak packages
  block:
    - name: Deploy service unit
      copy:
        dest: '{{ systemd_path }}/{{ service_name }}.service'
        content: |
          [Unit]
          Description={{ description }}
          [Service]
          Type=oneshot
          ExecStart="{{ flatpak_bin }}" --user update --noninteractive
        mode: '0644'
      notify: reload-systemd-user-daemon
    - name: Deploy timer unit
      copy:
        dest: '{{ systemd_path }}/{{ service_name }}.timer'
        content: |
          [Unit]
          Description={{ description }}
          [Timer]
          OnCalendar=*-*-* 04:00:00
          Persistent=true
          RandomizedDelaySec=1h
          [Install]
          WantedBy=timers.target
        mode: '0644'
      notify: reload-systemd-user-daemon
    - name: Enable & start timer
      systemd:
        name: '{{ service_name }}.timer'
        enabled: true
        state: started
        scope: user
