# MatchDevicePath "/dev/input/event*"
# Driver "libinput"

Section "InputClass"
        Identifier "pointer-catchall"
        MatchIsPointer "on"
	Option "NaturalScrolling" "true"
	# Option "LeftHanded" "true"
EndSection
