# user config
#
# use a config snippet that contains something like this:
#
# Section "InputClass"
#   Identifier "something or other"
#   MatchDriver "libinput"
#
#   MatchIsTouchpad "on"
#   ... other Match directives ...
#   Option "someoption" "value"
# EndSection
#
# This applies the option any libinput device also matched by the other directives. See the xorg.conf(5) man page for more info on
# matching devices.


##################################3
# KEYBOARD
##################################3


Section "InputClass"
        Identifier "custom keyboard catchall"
        MatchIsKeyboard "on"
        MatchDevicePath "/dev/input/event*"
	# NoMatchVendor "BlackC_Sayobot.cn|ZSA_Technology_Labs_Inc"
	# NoMatchProduct "ZSA Technology Labs Inc ErgoDox EZ Glow"
	# NoMatchVendor "BlackC Sayobot.cn"
	# NoMatchVendor "ZSA Technology Labs Inc"
	# NoMatchUSBID "3297:4976"
	# NoMatchUSBID "8089:0004"
	# NoMatchProduct "SayoDevice_6x4F|SayoDevice\x206x4F|SayoDevice 6x4F|SayoDevice 6x4F Keyboard|BlackC Sayobot.cn SayoDevice 6x4F Keyboard"
	# NoMatchProduct "SayoDevice 6x4F|SayoDevice 6x4F Keyboard|BlackC Sayobot.cn SayoDevice 6x4F Keyboard"
	# NoMatchProduct "SayoDevice 6x4F"
	Driver "libinput"
 	Option "XkbLayout" "us"
	Option "XkbVariant" "colemak_dh"
	Option "XkbOptions" "ctrl:nocaps,altwin:swap_lalt_lwin,korean:ralt_hangul"
EndSection

# Section "InputClass"
#         Identifier "BlackC Keyboard catchall"
#         MatchIsKeyboard "on"
#         MatchDevicePath "/dev/input/event4"
# 	# MatchProduct "SayoDevice 6x4F" # it works
# 	# MatchProduct "SayoDevice 6x4F|SayoDevice 6x4F Keyboard|BlackC Sayobot.cn SayoDevice 6x4F Keyboard"


# Section "InputClass"
#         Identifier "ZSA"
#         MatchIsKeyboard "on"
#         MatchDevicePath "/dev/input/event*"
# 	MatchUSBID "3297|4976|3297:4976"
# 	NoMatchProduct "SayoDevice_6x4F|SayoDevice\x206x4F|SayoDevice 6x4F|SayoDevice 6x4F Keyboard|BlackC Sayobot.cn SayoDevice 6x4F Keyboard"
# 	Driver "libinput"
# 	Option "XkbLayout" "us"
# 	Option "XkbVariant" "colemak_dh_matrix"
# 	Option "XkbOptions" ""
# EndSection
