#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# swap stack to tab if needed
# NOTE: splith is vsplit alike in vim

# LIMITATION:
#   CAN NOT HANDDLE when stacking/tabbed window are inside window

import collections
import logging
import sys
from typing import Optional

import i3ipc
from i3ipc import Connection, Event

logging.basicConfig(level=logging.DEBUG)
PROGRAM_NAME: str = "managing"

def print_rect(rect: i3ipc.con.Rect):
    print(rect.x, rect.y, rect.width, rect.height)

def print_container(container: i3ipc.Con, depth: int = 1):
    print("".join(["*" for _ in range(depth)]), end=" ")
    print(
        f"{container.id} {container.type} {container.layout} : ",
        f"{container.name} ({container.app_id}",
    )

    for node in container.nodes:
        print_container(node, depth + 1)


def print_workspace(con: Optional[i3ipc.Con] = None):

    # con = i3.get_tree().find_focused()

    if con:
        print_container(con.workspace())
    else:
        print("No focused window")


# class fixnodeinfo(Exception):
    # https://docs.python.org/3/faq/design.html#why-is-there-no-goto



if __name__ == "__main__":
    i3 = Connection()
    con = i3.get_tree().find_focused()
    print_workspace(con)
