context.modules = [
{   name = libpipewire-module-filter-chain
    args = {
        node.description =  "Noise Canceling Source Analog"
        media.name =  "Noise Canceling Source Analog"
        filter.graph = {
            nodes = [
                {
                    type = ladspa
                    name = rnnoise
                    plugin = /usr/lib/ladspa/librnnoise_ladspa.so
                    label = noise_suppressor_mono
                    control = {
                        "VAD Threshold (%)" = 02.0
                        "VAD Grace Period (ms)" = 800
                        "Retroactive VAD Grace (ms)" = 0
                    }
                }
            ]
        }
        capture.props = {
            node.name =  "capture.rnnoise_source"
	    node.target = "alsa_input.pci-0000_07_00.6.analog-stereo"
            node.passive = true
            audio.rate = 48000
        }
        playback.props = {
            node.name =  "rnnoise_source.usb-analog-stereo"
            media.class = Audio/Source
            audio.rate = 48000
        }
    }
}
]
