# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

#: Fonts {{{

#: kitty has very powerful font management. You can configure
#: individual font faces and even specify special fonts for particular
#: characters.

font_family      monospace
bold_font        auto
italic_font      auto
bold_italic_font auto

#: You can specify different fonts for the bold/italic/bold-italic
#: variants. To get a full list of supported fonts use the `kitty
#: list-fonts` command. By default they are derived automatically, by
#: the OSes font system. Setting them manually is useful for font
#: families that have many weight variants like Book, Medium, Thick,
#: etc. For example::

#:     font_family      Operator Mono Book
#:     bold_font        Operator Mono Medium
#:     italic_font      Operator Mono Book Italic
#:     bold_italic_font Operator Mono Medium Italic

font_size 11.0



#: }}}

#: Cursor customization {{{

cursor #5f87af

#: Default cursor color

cursor_text_color #444444

#: Choose the color of text under the cursor. If you want it rendered
#: with the background color of the cell underneath instead, use the
#: special keyword: background

cursor_shape block

#: The cursor shape can be one of (block, beam, underline)

cursor_blink_interval 0

#: The interval (in seconds) at which to blink the cursor. Set to zero
#: to disable blinking. Negative values mean use system default. Note
#: that numbers smaller than repaint_delay will be limited to
#: repaint_delay.

#: }}}

#: Window layout {{{

remember_window_size  no
initial_window_width  1528
initial_window_height 936

#: If enabled, the window size will be remembered so that new
#: instances of kitty will have the same size as the previous
#: instance. If disabled, the window will initially have size
#: configured by initial_window_width/height, in pixels. You can use a
#: suffix of "c" on the width/height values to have them interpreted
#: as number of cells instead of pixels.

#: }}}

#: Tab bar {{{

tab_bar_edge bottom

#: Which edge to show the tab bar on, top or bottom

tab_bar_margin_width 0.0

#: The margin to the left and right of the tab bar (in pts)

tab_bar_style fade

#: The tab bar style, can be one of: fade, separator or hidden. In the
#: fade style, each tab's edges fade into the background color, in the
#: separator style, tabs are separated by a configurable separator.

tab_bar_min_tabs 2

#: The minimum number of tabs that must exist before the tab bar is
#: shown

tab_switch_strategy previous

#: The algorithm to use when switching to a tab when the current tab
#: is closed. The default of previous will switch to the last used
#: tab. A value of left will switch to the tab to the left of the
#: closed tab. A value of last will switch to the right-most tab.

tab_fade 1

#: Control how each tab fades into the background when using fade for
#: the tab_bar_style. Each number is an alpha (between zero and one)
#: that controls how much the corresponding cell fades into the
#: background, with zero being no fade and one being full fade. You
#: can change the number of cells used by adding/removing entries to
#: this list.

active_tab_foreground   #444
active_tab_background   #eee
active_tab_font_style   bold-italic
inactive_tab_foreground #aaa
inactive_tab_background #eee
inactive_tab_font_style normal

#: Tab bar colors and styles

#: }}}


# gruvbox-dark colorscheme for kitty
# snazzy theme used as base

foreground            #ebdbb2
background            #272727
selection_foreground  #655b53
selection_background  #ebdbb2
url_color             #d65c0d

# black
color0   #272727
color8   #928373

# red
color1   #cc231c
color9   #fb4833

# green
color2   #989719
color10  #b8ba25

# yellow
color3   #d79920
color11  #fabc2e

# blue
color4  #448488
color12 #83a597

# magenta
color5   #b16185
color13  #d3859a

# cyan
color6   #689d69
color14  #8ec07b

# white
color7   #a89983
color15  #ebdbb2
