" Navi 의 cheat 와는 다르다!

" Generated by cluade-3-5-sonnet

" Vim syntax file
" Language: docopt
" Maintainer: Your Name
" Latest Revision: 2023

if exists("b:current_syntax")
    finish
endif

" Comments (must be defined before other syntax rules)
syntax match docoptComment "#.*$"

" Keywords
syntax keyword docoptKeyword Usage Options contained
syntax keyword docoptOption contained skipwhite
    \ -h --help --version

" URLs
syntax match docoptUrl '\(http\|https\|ftp\)://[[:alnum:]%/?=_&.-]*'

" Patterns
" Program name at the start of usage line
syntax match docoptProgram '^\s\+\zs\S\+' contained

" Arguments in angle brackets
" syntax match docoptArgument '<[^>]\+>'

" Arguments in `
syntax match docoptArgument '`[^`]\+`'

" Options with possible values
syntax match docoptOptionWithValue '--\w\+=[<][^>]\+[>]'
syntax match docoptOptionWithValue '-\w\+=[<][^>]\+[>]'

" Short and long options
syntax match docoptOption '\(--\|\-\)\w\+'

" Special syntax elements
syntax match docoptDelimiter '|' contained
syntax match docoptDelimiter '(' contained
syntax match docoptDelimiter ')' contained
syntax match docoptDelimiter '\[' contained
syntax match docoptDelimiter '\]' contained
syntax match docoptEllipsis '\.\.\.' contained

" Usage section
syntax region docoptUsageSection start="^Usage:" end="^\ze\S"
    \ contains=docoptKeyword,docoptProgram,docoptOption,docoptOptionWithValue,
    \ docoptArgument,docoptDelimiter,docoptEllipsis

" Options section
syntax region docoptOptionsSection start="^Options:" end="^\ze\S"
    \ contains=docoptKeyword,docoptOption,docoptOptionWithValue,
    \ docoptArgument,docoptDelimiter

" Default values
syntax match docoptDefault '\[default:.\{-}\]'

" Highlighting links
highlight link docoptComment Comment
highlight link docoptKeyword Keyword
highlight link docoptProgram Identifier
highlight link docoptOption Statement
highlight link docoptOptionWithValue Statement
highlight link docoptArgument Type
highlight link docoptDelimiter Delimiter
highlight link docoptEllipsis Special
highlight link docoptDefault Comment
highlight link docoptUrl Underlined

let b:current_syntax = "docopt"
