- name: Setup systemd user tmpfiles
  hosts: localhost
  become: false
  vars:
    xdg_config_home: "{{ ansible_env.XDG_CONFIG_HOME | default(ansible_env.HOME + '/.config') }}"
  tasks:
    - name: Ensure user-tmpfiles.d directory exists
      file:
        path: "{{ xdg_config_home }}/user-tmpfiles.d"
        state: directory
        mode: '0755'
    - name: Deploy tmpfile 10-cleanup.conf
      copy:
        content: |
          R {{ ansible_env.HOME }}/.bash_history - - - -
          R {{ ansible_env.HOME }}/.mypy_cache - - - -
          R {{ ansible_env.HOME }}/.psql_history - - - -
          R {{ ansible_env.HOME }}/.python_history - - - -
          R {{ ansible_env.HOME }}/.vim - - - -
          R {{ ansible_env.HOME }}/.viminfo - - - -
          R {{ ansible_env.HOME }}/.wget-hsts - - - -
          R {{ ansible_env.HOME }}/.zsh_history - - - -
        dest: "{{ ansible_env.HOME }}/.config/user-tmpfiles.d/10-cleanup.conf"
        mode: '0644'
