Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us"
        Option "XkbVariant" "colemak_dh"
        Option "XkbOptions" "ctrl:nocaps,altwin:swap_lalt_lwin,korean:ralt_hangul"
EndSection
