Section "InputClass"
        Identifier "system-touchpad"
        MatchIsTouchpad "on"
	Option "NaturalScrolling" "true"
	Option "DisableWhileTyping" "true"
	Option "Tapping" "true"
	Option "TappingDrag" "true"
EndSection

Section "InputClass"
        Identifier "system-pointer"
        MatchIsPointer "on"
	Option "NaturalScrolling" "true"
EndSection
