#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#

[options]
BottomUp
# Print search results from Buttom to top
Devel
# During sysupgrade check AUR developemnt packages for updates
CleanAfter
NewsOnUpgrade
SortBy = popularity
SkipReview
