# comm.variables
################################################################################
# NOTE: DO NOT USE "" to set executable variables : i3 reports error

set $border_px 3

## Logo key. Use Mod1 for Alt. Mod4 for super
set $mod Mod4

# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l

set $term footclient
# set $term foot
# set $term qterminal
# set $term wezterm
# set $term gnome-terminal
# set $term termite
# set $term $TERMINAL

# Your preferred application launcher
# Note: pass the final command to swaymsg so that the resulting window can be opened
# on the original workspace that the command was run on.
# set $menu dmenu_path | dmenu | xargs swaymsg exec --

# set $menu "albert show"
# set $menu "wofi"
set $menu "ulauncher-toggle"


set $clipboard clipmenu -font "Monospace 26" -hide-scrollbar
# set $emoji rofi -show emoji -modi emoji
set $program-relauncher $HOME/.local/bin/__program-relauncher
# set $classic_menu $HOME/.local/bin/__rofi-launcher
# set $powermenu $HOME/.local/bin/__rofi-power-menu
# set $setting_menu $HOME/.local/bin/__rofi-settings

# vim:ft=conf
