# comm.autostart.conf
###################################################################################

# Polkit Agent
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Gnome - Keyring
exec --no-startup-id gnome-keyring-daemon --start --components=pkcs11
exec --no-startup-id gnome-keyring-daemon --start --components=secrets
exec --no-startup-id gnome-keyring-daemon --start --components=ssh

# geoclue: xdg-desktop-portal 의존 패키지
# exec --no-startup-id /usr/lib/geoclue-2.0/demos/agent
# exec --no-startup-id /usr/lib/pam_kwallet_init

# exec --no-startup-id ~/.config/sway/scripts/xdg-desktop-portal-fix.sh
exec --no-startup-id pcmanfm-qt -d

exec_always --no-startup-id xrdb -merge "$HOME/.Xresources"

# vim:ft=conf
