# vim:ft=conf

# NOTE: swayidle의 설정은 별도 설정 파일로 저장.
exec --no-startup-id swayidle -w
exec --no-startup-id "$HOME/.config/sway/auto-manager/popup-enabler"

# reset gtk-setting
exec_always --no-startup-id gsettings reset org.gnome.desktop.interface scaling-factor
exec_always --no-startup-id gsettings reset org.gnome.desktop.interface cursor-size
