# comm.gtk-theme
# vim:ft=conf

# gtk-theme
################################################################################
# exec_alwaysi gsettings set org.gnome.desktop.interface icon-theme 'Newaita-dark'
exec --no-startup-id gsettings set org.gnome.desktop.interface icon-theme 'Fluent-dark'
# exec --no-startup-id gsettings set org.gnome.desktop.interface icon-theme 'breeze'
# exec --no-startup-id gsettings set org.gnome.desktop.interface icon-theme 'Adwaita'

exec --no-startup-id gsettings set org.gnome.desktop.interface cursor-theme 'capitaine-cursors-light'
exec --no-startup-id gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec --no-startup-id gsettings set org.gnome.desktop.interface gtk-theme 'Adw-dark'
exec --no-startup-id gsettings set org.gnome.desktop.interface document-font-name 'Sans Serif 11'
exec --no-startup-id gsettings set org.gnome.desktop.interface font-name 'Sans Serif 10'
exec --no-startup-id gsettings set org.gnome.desktop.interface monospace-font-name 'Monospace 10'
exec --no-startup-id gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu'
# $exec_alwaysi gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/IMModule':<'fcitx5'>}"

# sway
#################################################################################
gaps inner 6
default_border pixel $border_px

# gruvbox theme (by me)
client.focused           #458588 #458588 #FFFFFF
client.focused_inactive  #303030 #303030 #eeeeec
client.unfocused         #424242 #424242 #eeeeec
client.urgent            #cc241d #cc241d #d3869b

# theme (Adwaita-dark from https://gist.github.com/voodoojello/9138ed6f43d1a022a7e41033eca69427)
#                        border     bg         fg         indicator  child_border
# client.focused           #15539e    #15539e    #e0e0e0    #00ff00    #202332
# client.focused_inactive  #383c4a    #383c4a    #e0e0e0    #00ff00    #202332
# client.unfocused         #383c4a    #383c4a    #808080    #00ff00    #202332
# client.urgent            #383c4a    #900000    #ffffff    #00ff00    #202332
# client.placeholder       #383c4a    #0c0c0c    #ffffff    #00ff00    #202332
# client.background        #1e1e1e #1e1e1e #1e1e1e

# code-dark
# client.unfocused         #1e1e1e #1e1e1e #eeeeec
