#
# bindsym $mod+Shift+c reload, $execi "notify-send i3 reloaded"
bindsym $mod+Shift+c \
	reload, \
	exec --no-startup-id "$HOME/.local/bin/__i3-update", \
	exec --no-startup-id "notify-send sway reloaded"

# no restart feature in sway
bindsym $mod+Shift+r \
	exec --no-startup-id "$HOME/.local/bin/__wlroots-auto-randr", \
	exec --no-startup-id "$HOME/.local/bin/__i3-update", \
	exec --no-startup-id "notify-send sway reloaded"


# bindsym XF86TouchpadToggle $execi "swaymsg input type:touchpad events toggle enabled disabled && notify-send 'XF86TouchpadToggel' 'Touchpad Toggle'"
