#
# bindsym $mod+Shift+c reload, $execi "notify-send i3 reloaded"
bindsym $mod+Shift+c reload, $execi "$HOME/.local/bin/__i3-update", $execi "notify-send sway reloaded"

# no restart feature in sway
bindsym $mod+Shift+r reload, $execi "$HOME/.local/bin/__i3-update", $execi "notify-send sway reloaded"


# bindsym XF86TouchpadToggle $execi "swaymsg input type:touchpad events toggle enabled disabled && notify-send 'XF86TouchpadToggel' 'Touchpad Toggle'"
