# sway.assgin
assign [app_id="todoist-*"] → $ws8
assign [app_id="thunderbird" title=".*- Mozilla Thunderbird"] → $ws9
assign [app_id="spotify-qt"] → $ws10
assign [app_id="gnome-terminal-server" title="Spotify TUI"] → $ws10
