# sway.for-window
########################################################################

# NOTE: swaymsg -t get_tree | grep "app_id"

# No titlebar
# for_window [app_id="firefox"] border pixel $border_px
# for_window [app_id="foot"] border pixel $border_px
# for_window [app_id=".*"] border pixel $border_px


# 1password
for_window [app_id="1Password"] move scratchpad, scratchpad show

# == Floating Disable ==
for_window [class="explorer.exe" shell="xwayland"] \
	floating disable, fullscreen disable
for_window [shell="xwayland" class="Spotify"] floating disable

# == floating enable border none ==
# for_window [shell="xwayland"] floating enable
# for_window [app_id="com.github.alainm23.planner"] border csd
for_window [app_id="ulauncher"] floating enable, border none
for_window [app_id="ulauncher"] move up 280px
for_window [app_id="albert"] floating enable, border none
for_window [app_id="albert"] move up 160px
for_window [app_id="nm-connection-editor"] floating enable
for_window [app_id="nmtui" title="nmtui"] floating enable

# floating enable, border default
for_window [app_id="blueman-manager"] floating enable
for_window [app_id="gcr-viewer"] floating enable # cert viewer
for_window [app_id="org.fcitx.fcitx5-config-qt"] floating enable
for_window [app_id="fcitx-config-gtk3"] floating enable
for_window [app_id="copyq"] floating enable
for_window [app_id="pavucontrol"] floating enable
for_window [app_id="bottles"] floating enable
for_window [app_id="org.kde.kdeconnect.app"] floating enable
for_window [app_id="python3" title="dupeGuru"] floating enable
for_window [app_id="syncthing-gtk"] floating enable
for_window [app_id="qalculate-gtk"] floating enable
# for_window [app_id="qalculate-gtk"] resize set width 400px, resize set hegiht 700px
for_window [app_id="gnome-pomodoro"] floating enable

# floating enable, border pixel $border_px
for_window [app_id="lutris"] \
	floating enable, border pixel $border_px
for_window [app_id="xdg-desktop-portal-gtk"] \
	floating enable, border pixel $border_px
for_window [app_id="nextcloud"] \
	floating enable, border none, resize set width 480px, move position cursor

# BORDER NORMAL
# for_window [floating app_id="albert" title="Settings.*"] border normal
# for_window [floating app_id="albert" title="Property.*"] border normal
# for_window [floating app_id="blueman-manager"] border normal
# for_window [floating app_id="copyq"] border normal
# for_window [floating app_id="pavucontrol"] border normal
# for_window [floating app_id="virt-manager"] border normal
# for_window [floating app_id="nm-connection-editor"] border normal
# for_window [floating app_id="thunderbird"] border normal
# for_window [app_id="gedit"] border pixel $border_px

# BORDER NONE
# for_window [app_id="syncthing-gtk"] border none
# for_window [app_id="org.gnome.*"] border csd
# for_window [app_id="com.github.alainm23.planner"] border NONE
# for_window [app_id="bottles"] border none

# == X11 설정이 너무 커서 덮어 쓰기 ==
for_window [class="1Password" title="H.*1Password"] \
	resize set width 1000px height 720px, move position center
for_window [class="1Password" title="1Password"] floating enable, \
	resize set width 784px height 400px, move position center
for_window [class="1Password" title="Lock Screen — 1Password"] floating enable, \
	resize set width 784px height 400px, move position center
for_window [class="kakaotalk.exe"] floating enable, border none
for_window [class="kakaotalk.exe"] resize set width 50px height 300px
for_window [window_role="GtkFileChooserDialog"] resize set width 800px

# Misc
# for_window [instance="urxvt"] opacity 0.01
