# comm.late-autostart
################################################################################

# exec_always --no-startup-id brightnessctl --device=asus::kbd_backlight set 3

# dunst 실행안해도 자동으로 불러들이는 듯 (2020-12-06)
# dunst는 i3 restart 해도 살아있어서 다시 시작할 필요 없음 (2021-11-03)
exec_always --no-startup-id $program-relauncher swaync

# exec --no-startup-id clipmenud
# exec_always --no-startup-id clipcatd
# $execi autocutsel -fork
# $execi autocutsel -selection PRIMARY -fork

# exec --no-startup-id gammastep
exec_always --no-startup-id fcitx5 -rd

# Late Start
exec_always --no-startup-id $program-relauncher ulauncher --hide-window
exec_always --no-startup-id $program-relauncher blueman-applet
exec_always --no-startup-id $program-relauncher nm-applet --indicator
# exec_always --no-startup-id $program-relauncher albert
exec_always --no-startup-id $program-relauncher 1password --silent
exec_always --no-startup-id $program-relauncher firewall-applet

exec_always --no-startup-id $program-relauncher copyq

exec_always --no-startup-id $program-relauncher syncthing-gtk --minimized

# exec --no-startup-id spotifyd
# exec systemctl --user start spotifyd

##################
# python 프로그램이라 _program-relauncher 안먹음
# exec sleep 2; gammastep-indicator
# exec_always --no-startup-id __program-relauncher.sh gammastep-indicator

exec --no-startup-id gtk-launch thunderbird
exec --no-startup-id gtk-launch firefox
exec --no-startup-id gtk-launch org.kde.konsole

exec_always --no-startup-id brightnessctl --device=asus::kbd_backlight set 0
