-- ---@type LazySpec
-- return {
--   [1] = "folke/noice.nvim",
--   optional = true,
--   opts = function(_, opts)
--     if not opts.signature then
--       opts.signature = {}
--     end
--
--     opts.signature.enabled = true
--   end,
-- }
