#!/usr/bin/env -S just --justfile

set fallback := true

_:
    @just --list

build:
    for t in config/my-templates/tinted-*; do tinty build "$t"; done

build-legacy-maybe:
    #!/usr/bin/env bash
    # Creates tinted-theming/my-templates/tinted-*/themes/base24-*

    set -euo pipefail

    XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"

    templates="${XDG_CONFIG_HOME}/tinted-theming/my-templates"
    myschemes="${XDG_CONFIG_HOME}/tinted-theming/my-schemes"

    if [ ! -d "$templates" ] || [ ! -d "$myschemes" ]; then
        echo "ERROR: $templates or $myschemes is not installed" >&2
        exit 1
    fi

    for template in "$templates"/*; do
        .lib/tinted-builder-rust/bin/tinted-builder-rust build -s "$myschemes" "$template"
    done
