#!/usr/bin/env -S just --justfile

set fallback := true

_:
    @just --list

build:
    for t in config/my-templates/tinted-*; do tinty build "$t"; done

sync:
    tinty install
    tinty sync # sync with git repo

update-remote-git-repo:
    tinty update

list-my-schemes:
    tinty list --custom-schemes

generate-themes-from-custom-schemes:
    tinty init
