---@type LazySpec[]
return {
  { [1] = "neoconf.nvim",                enabled = false },

  { [1] = "nvim-treesitter",             enabled = false },
  { [1] = "nvim-treesitter-context",     enabled = false },
  { [1] = "nvim-treesitter-textobjects", enabled = false },

  { [1] = "statuscol.nvim",              enabled = false },
  { [1] = "nui.nvim",                    enabled = false },
  { [1] = "noice.nvim",                  enabled = false },
  { [1] = "lualine.nvim",                enabled = false },
  { [1] = "bufferline.nvim",             enabled = false },

  { [1] = "flash.nvim",                  enabled = false },
  { [1] = "nvim-surround",               enabled = false },
  { [1] = "mini.ai",                     enabled = false },
  { [1] = "nvim-lint",                   enabled = false },
  { [1] = "overseer.nvim",               enabled = false },
  { [1] = "trouble.nvim",                enabled = false },
  { [1] = "ts-comments.nvim",            enabled = false },
  { [1] = "vimtex",                      enabled = false },
  { [1] = "vim-sleuth",                  enabled = false },
  { [1] = "windows.nvim",                enabled = false },
  { [1] = "aerial.nvim",                 enabled = false },
  { [1] = "cmp-nvim-lsp",                enabled = false },
  { [1] = "conform.nvim",                enabled = false },
  { [1] = "vim-better-whitespace",       enabled = false },
  { [1] = "gitsigns.nvim",               enabled = false },
  { [1] = "gp.nvim",                     enabled = false },
  { [1] = "fzf-lua",                     enabled = false },
  { [1] = "fcitx",                       enabled = false },
  { [1] = "nvim-cmp",                    enabled = false },
  { [1] = "todo-comments.nvim",          enabled = false },
  { [1] = "which-key.nvim",              enabled = false },
  { [1] = "nvim-ts-autotag",             enabled = false },
  { [1] = "none-ls.nvim",                enabled = false },
  { [1] = "mini.hipatterns",             enabled = false },
  { [1] = "mini.icons",                  enabled = false },
  { [1] = "mini.pairs",                  enabled = false },
  { [1] = "marks.nvim",                  enabled = false },
  { [1] = "LuaSnip",                     enabled = false },
  { [1] = "tagbar",                      enabled = false },
  { [1] = "toggleterm.nvim",             enabled = false },
  { [1] = "obsidian.nvim",               enabled = false },
  { [1] = "lazydev.nvim",                enabled = false },
  { [1] = "inc-rename.nvim",             enabled = false },
  { [1] = "grug-far.nvim",               enabled = false },
  { [1] = "fidget.nvim",                 enabled = false },
  { [1] = "dropbar.nvim",                enabled = false },
  { [1] = "global-note.nvim",            enabled = false },
  { [1] = "catppuccin",                  enabled = false },
  { [1] = "Comment.nvim",                enabled = false },
  { [1] = "neogen",                      enabled = false },
  { [1] = "diffview.nvim",               enabled = false },
  { [1] = "hurl.nvim",                   enabled = false },
  { [1] = "neotest",                     enabled = false },
  { [1] = "nvim-jdtls",                  enabled = false },
  { [1] = "markdown-preview.nvim",       enabled = false },
  { [1] = "nvim-window-picker",          enabled = false },
  { [1] = "copilot.lua",                 enabled = false },
  { [1] = "CopilotChat.nvim",            enabled = false },
  { [1] = "dial.nvim",                   enabled = false },

  { [1] = "crates.nvim",                 enabled = false },
  { [1] = "rustaceanvim",                enabled = false },
  { [1] = "SchemaStore.nvim",            enabled = false },
  { [1] = "tagbar",                      enabled = false },
  { [1] = "vim-gutentags",               enabled = false },
  { [1] = "vim-dadbod",                  enabled = false },
  { [1] = "vim-dadbod-completion",       enabled = false },
  { [1] = "vim-dadbod-ui",               enabled = false },
  { [1] = "typst-preview.nvim",          enabled = false },
  { [1] = "tokyonight.nvim",             enabled = false },
  { [1] = "persistence.nvim",            enabled = false },
  { [1] = "render-markdown.nvim",        enabled = false },

  { [1] = "nvim-nio",                    enabled = false },

  -- core
  -- { [1] = "gruvbox.nvim",                enabled = false },
  -- { [1] = "LazyVim",                     enabled = false },
  { [1] = "snacks.nvim",                 enabled = false },
  -- { [1] = "plenary.nvim",                enabled = false },
  -- { [1] = "nvim-lspcofnig",              enabled = false },
  -- { [1] = "mason-lspconfig.nvim",        enabled = false },
  -- { [1] = "mason.nvim",                  enabled = false },
}
