# THIS IS EXPERIMENTAL
# the config file schema may change at any time

style:
  tag:
    color: cyan # text color. possible values: https://bit.ly/3gloNNI
    width_percentage: 1 # column width relative to the terminal window
    min_width: 10 # minimum column width as number of characters
  comment:
    color: blue
    width_percentage: 42
    min_width: 45
  snippet:
    # width_percentage: 45
    width_percentage: 45
    color: white
finder:
  command: fzf # equivalent to the --finder option
  # overrides: --tac # equivalent to the --fzf-overrides option
  # overrides_var: --tac # equivalent to the --fzf-overrides-var option
# cheats:
#   paths:
#     - /path/to/some/dir # on unix-like os
#     - F:\\path\\to\\dir # on Windows
# path: /path/to/some/dir # (DEPRECATED) equivalent to the --path option

# search:
# tags: git,!checkout # equivalent to the --tag-rules option
shell:
  # Shell used for shell out. Possible values: bash, zsh, dash, ...
  # For Windows, use `cmd.exe` instead.
  command: dash
  finder_command: dash # similar, but for fzf's internals
