# NOTE:
#   - following version 0.1.2 of base24 <2026-01-05>
#   - <https://github.com/tinted-theming/base24/blob/main/styling.md>
#
# Base24: Gruvbox Light
# Scheme by Tinted Theming (https://github.com/tinted-theming), morhetz (https://github.com/morhetz/gruvbox)

[colors]
foreground = "#3c3836"
background = "#fbf1c7"
visual_bell = "#d5c4a1"

selection_bg = "#d5c4a1"
selection_fg = "#3c3836"

cursor_bg = "#3c3836"
cursor_fg = "#fbf1c7"
cursor_border = "#3c3836"

scrollbar_thumb = "#ebdbb2"
split = "#bdae93"           # or use base02 if too bright

ansi = [
  "#fbf1c7",
  "#cc241d",
  "#98971a",
  "#d79921",
  "#458588",
  "#b16286",
  "#689d6a",
  "#282828",
]

brights = [
  "#bdae93",
  "#9d0006",
  "#79740e",
  "#b57614",
  "#076678",
  "#8f3f71",
  "#427b58",
  "#1d2021",
]

# Since: 20220319-142410-0fcdea07
# When the IME, a dead key or a leader key are being processed and are effectively
# holding input pending the result of input composition, change the cursor
# to this color to give a visual cue about the compose state.
compose_cursor = "#d65d0e" # orange

# Colors for copy_mode and quick_select
# available since: 20220807-113146-c2fee766
# In copy_mode, the color of the active text is:
# 1. copy_mode_active_highlight_* if additional text was selected using the mouse
# 2. selection_* otherwise
[colors.copy_mode_active_highlight_bg]
Color = "#d79921" # search-text-background
[colors.copy_mode_active_highlight_fg]
Color = "#fbf1c7"
[colors.copy_mode_inactive_highlight_bg]
Color = "#d5c4a1" # selection-background
[colors.copy_mode_inactive_highlight_fg]
Color = "#3c3836"

[colors.quick_select_label_bg]
Color = "#458588" # blue
[colors.quick_select_label_fg]
Color = "#fbf1c7"
[colors.quick_select_match_bg]
Color = "#d79921"
[colors.quick_select_match_fg]
Color = "#fbf1c7" # search-text-background

[colors.input_selector_label_bg]
Color = "#ebdbb2"
[colors.input_selector_label_fg]
Color = "#3c3836"

[colors.launcher_label_bg]
Color = "#ebdbb2"
[colors.launcher_label_fg]
Color = "#3c3836"

[colors.indexed]
16 = "#d65d0e"
17 = "#9d0006"
18 = "#ebdbb2"
19 = "#d5c4a1"
20 = "#7c6f64"
21 = "#3c3836"

# vi:ft=toml
