shell = "bash -c '{}'"
default-scheme = "base24-my-gruvbox-light"
preferred-schemes = ["base24-my-gruvbox-light"]
hooks = ["echo \"The current scheme is: $(tinty current)\""]

[[items]]
path = "~/.config/tinted-theming/my-templates/tinted-alacritty"
name = "alacritty"
themes-dir = "themes"
hook = "cp -f %f ~/.config/alacritty/_base16.toml && touch ~/.config/alacritty/alacritty.toml"
supported-systems = ["base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "ghostty"
themes-dir = "themes/ghostty"
hook = "command cp -f %f ~/.config/ghostty/themes/_base16"
supported-systems = ["base24"]

[[items]]
path = "https://github.com/tinted-theming/tinted-nvim"
name = "nvim"
themes-dir = "lua/colors"
hook = "command cp -f %f ~/.config/nvim/lua/_base24.lua"
supported-systems = ["base24"]
