shell = "bash -c '{}'"
default-scheme = "base24-my-gruvbox-light"
preferred-schemes = ["base24-my-gruvbox-light"]
hooks = ["echo \"The current scheme is: $(tinty current)\""]

[[items]]
path = "~/.config/tinted-theming/my-templates/tinted-alacritty"
name = "alacritty"
themes-dir = "themes"
hook = "cp -f %f ~/.config/alacritty/_base16.toml && touch ~/.config/alacritty/alacritty.toml"
supported-systems = ["base24"]
