# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!
#
# This config file uses keycodes (bindsym) and was written for the QWERTY
# layout.
#
# To get a config file with the same key positions, but for your current
# layout, use the i3-config-wizard
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# DO NOT TOUCH THIS FILE
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
