# i3wm.gtk-settings
################################################################################

$exec_alwaysi gsettings set org.gnome.desktop.interface scaling-factor 2
$exec_alwaysi gsettings set org.gnome.desktop.interface cursor-size 48

# exec_always --no-startup-id gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gdk/WindowScalingFactor': <2>}"
