# i3wm.theme
################################################################################

gaps inner 4
# smart_borders on : deprecated?? 2021-11-04 Not Listed in docs
# hide_edge_borders --i3 none # i3 에서는 작동하지 않음.

font pango:FontAwesome, monospace 10.1
# font pango:MesloLGS Nerd Font Mono 21
# Pretendard 19

# border & floating
# default_border pixel 5
# default_border normal|none|pixel <px>
# default_border pixel $border_px
default_border pixel $border_px
