# vim:ft=conf
# exec systemctl --user import-environment DISPLAY=":0" WAYLAND_DISPLAY="wayland-1" SWAYSOCK XDG_CURRENT_DESKTOP=sway
exec --no-startup-id \
       systemctl --user import-environment \
       DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP=sway

exec --no-startup-id \
       hash dbus-update-activation-environment 2>/dev/null && \
       dbus-update-activation-environment \
       --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP=sway

# exec --no-startup-id sh -c '/usr/lib/xdg-desktop-portal -vr & /usr/lib/xdg-desktop-portal-wlr -l DEBUG 2>&1 | tee /home/hyunjae/xdpw2.log'
# exec hash dbus-update-activation-environment 2>/dev/null && \
#
#      dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP


# Stop any services that are running, so that they receive the new env var when they restart.
# systemctl --user stop pipewire pipewire-media-session xdg-desktop-portal xdg-desktop-portal-wlr xdg-desktop-portal-kde xdg-desktop-portal-gtk xdg-desktop-portal-gnome
# systemctl --user start pipewire-media-session
exec_always --no-startup-id killall dunst
exec_always --no-startup-id _program-relauncher.sh mako

exec_always lxqt-policykit-agent

# KDE Apps.. for testing purpose
# exec --no-startup-id xembedsniproxy
# exec --no-startup-id /usr/lib/polkit-kde-authentication-agent-1

# swayidle: 별도 설정 파일로 저장.
exec --no-startup-id swayidle -w
