# variables
################################################################################

# vim:ft=conf
### Variables

## Logo key. Use Mod1 for Alt. Mod4 for super
set $mod Mod4
set $execi exec --no-startup-id
set $exec_alwaysi exec_always --no-startup-id

# Home row direction keys, like vim
set $left h
set $down j
set $up k
set $right l


# set $term footclient
set $term konsole
# set $term termite
# set $term $TERMINAL

# Your preferred application launcher
# Note: pass the final command to swaymsg so that the resulting window can be opened
# on the original workspace that the command was run on.
# set $menu dmenu_path | dmenu | xargs swaymsg exec --

set $menu "albert show"
set $clipboard clipmenu -font "Monospace 26" -hide-scrollbar
set $emoji rofi -show emoji -modi emoji
set $launcher "$HOME/.config/rofi/launchers/ribbon/launcher.sh"
set $classic_menu "__rofi-launcher.sh"
set $powermenu "__rofi-power-menu.sh"
set $setting_menu "__rofi-settings.sh"
set $program-relauncher "__program-relauncher.sh"
# set $volume_control "__volume-control.sh"
