### Output configuration
#
# man 5 sway-output
#
# Default wallpaper (more resolutions are available in /usr/share/backgrounds/sway/)
output * {
	# bg /usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png fill
	bg "$HOME/.local/share/wallpaper.jpg" fit "#111111"
	scale 2
	scale_filter smart
        adaptive_sync on
}
output eDP-1 {
# dpi 188.28
# 2560x1440 15.6in
# Target Relative display Size 1600x900 - scale 1.60
# Target Relative display Size 1504x846 - scale 1.666666667
# Target Relative display Size 1472x828 - scale 1.739130435
# Target Relative display Size 1312x738 - scale 1.951219512
# 96dpi - scale 1.96125

# 1312x738 -- 96.49 DPI
# Target Relative display Size 1280x720 - scale 2 (87.89dpi)
	enable
        mode "2560x1440@165.003Hz"
	scale 1.6

	# scale 2
	# scale 1.951219512
        # scale 1.666666667
        # scale 1.6
	# position 0 190
}

# BenQ PD2700U
output "BenQ Corporation BenQ PD2700U ET83K02766SL0" {
# dpi 163.18
# 3840x2160 27in (23.53" × 13.24")
# Target Relative display size 2560x1440 - scale 1.5
# Target Relative display size 2304x1296 - scale 1.666666667
# - 96 dpi - scale scale 1.699791667 (app 2260x1271)
# - 96 dpi (23 inch FHD monitor)
# Target Relative display size 2176x1224 - scale 1.764705882
# Target Relative display size 2048x1152 - scale 1.875 (105dpi)
# 72pixel
	enable
        mode "3840x2160@60.000Hz"
        # scale 1.764705882
	# scale 1.875
	scale 1.764705882

# 	# scale 1.702127660
        # scale 1.875
# 	# scale 1.8
	# scale 2.162162162
	# scale 2.352941176
}
# 2208x1242
#
#
# Example configuration:
#
#	output HDMI-A-1 resolution 1920x1080 position 1920,0
#
# You can get the names of your outputs by running: swaymsg -t get_outputs
