# vim:ft=conf
### Input configuration
#
# Example configuration:
#
#   input "2:14:SynPS/2_Synaptics_TouchPad" {
#       dwt enabled
#       tap enabled
#       natural_scroll enabled
#       middle_emulation enabled
#   }
#
# You can get the names of your inputs by running: swaymsg -t get_inputs
# Read `man 5 sway-input` for more information about this section.
# xkb_options "altwin:swap_lalt_lwin,ctrl:nocaps,shift:both_capslock"

	# xkb_options "altwin:swap_lalt_lwin,ctrl:nocaps"
input * {
        accel_profile flat
	tap enabled
	# tap_button_map lmr
	natural_scroll enabled
	dwt enabled
}

# ctrl:nocaps 해도 한글에서는 ctrl 이 먹지 않는다.
input "type:keyboard" {
	xkb_layout us
	xkb_model pc105
	xkb_variant colemak_dh
	# xkb_options "altwin:swap_lalt_lwin"
        xkb_options "ctrl:nocaps,altwin:swap_lalt_lwin,korean:ralt_hangul"
# ,ctrl:swap_rwin_rctl
# altwin:swap_lalt_lwin
# ctrl:rctrl_ralt"
        # xkb_options "caps:escape,altwin:swap_lalt_lwin,korean:ralt_hangul,ctrl:rctrl_ralt"
        # xkb_options "altwin:swap_lalt_lwin,korean:ralt_hangul,ctrl:rctrl_ralt"
}
input "type:touchpad" {
        accel_profile adaptive
	tap enabled
	natural_scroll enabled
	dwt enabled
}

# input "12951:18806:ZSA_Technology_Labs_Inc_ErgoDox_EZ_Glow_Keyboard" {
#         xkb_options "altwin:swap_lalt_lwin"
# }
# input "12951:18806:ZSA_Technology_Labs_Inc_ErgoDox_EZ_Glow_Consumer_Control" {
#         xkb_options "altwin:swap_lalt_lwin"
#         # natural_scroll disabled
# }
# input "12951:18806:ZSA_Technology_Labs_Inc_ErgoDox_EZ_Glow_System_Control" {
#         xkb_options "altwin:swap_lalt_lwin"
# }

# xkboptions 은 per-keyboard에 적용해도 fcitx에는 그렇게 handle 못해서 의미 없다!
#
# 실제 적용되는 키보드
# input "12951:18806:ZSA_Technology_Labs_Inc_ErgoDox_EZ_Glow" {
# 	xkb_layout us
# 	xkb_model pc105
# 	xkb_variant colemak_dh_matrix
#         # xkb_options ""
#         # xkb_options "caps:backspace,altwin:swap_lalt_lwin,korean:ralt_hangul,ctrl:rctrl_ralt"
#         # xkb_options "capslock:swayescape,altwin:swap_lalt_lwin,korean:ralt_hangul,ctrl:rctrl_ralt"
#         # xkb_options "capslock:backspace,altwin:swap_lalt_lwin,korean:ralt_hangul,ctrl:rctrl_ralt"
# }

input "32905:4:BlackC_Sayobot.cn_SayoDevice_6x4F_Keyboard" {
	xkb_layout us
	xkb_model pc105
	xkb_variant ""
        xkb_options ""
	# xkb_model nokiasu8w
}

input "1133:45089:Logi_Pebble_Mouse" {
        accel_profile flat
	natural_scroll enabled
        left_handed enabled
}
