# workspace-and-settings
################################################################################

focus_follows_mouse no
# = Workspaces =
set $ws1 "1 "
set $ws2 "2 "
set $ws3 "3 "
set $ws4 "4 "
set $ws5 "5 "
set $ws6 "6 "
set $ws7 "7 "
set $ws8 "8 "
set $ws9 "9 "
set $ws10 "10 "
#
# nf-fa 먼저 쓰자
#nf-mdi 쓰면 아이콘이 숫자 보다 먼저 뜨는 이상 현상 뜰때가 있음.특히: ﮷
# putting workspace on specific screens
workspace $ws1 output primary
workspace $ws2 output primary
workspace $ws3 output primary
workspace $ws4 output primary
workspace $ws5 output primary
workspace $ws6 output primary
workspace $ws7 output primary
# workspace $ws8 output primary
# workspace $ws9 output eDP-1
# workspace $ws10 output DP-2.1
