#
# Status Bar:
#
# Read `man 5 sway-bar` for more information about this section.
# bar {
# 	 position top

# 	 # When the status_command prints a new line to stdout, swaybar updates.
# 	 # The default just shows the current date and time.
# 	 status_command while date +'%Y-%m-%d %l:%M:%S %p'; do sleep 1; done

# 	 colors {
# 		  statusline #ffffff
# 		  background #323232
# 		  inactive_workspace #32323200 #32323200 #5c5c5c
# 	 }
# }
bar {
	swaybar_command waybar
}
# = AUTOSTART CONFIG  =
#
# $execi waybar
# exec_always --no-startup-id program-relauncher.sh waybar
# exec_always --no-startup-id program-relauncher.sh waybar
# exec --no-startup-id ~/.config/sway/scripts/start-waybar.sh
# exec --no-startup-id waybar
# exec_always --no-startup-id "program-relauncher.sh" waybar
