# X11 Assign Windows
################################################################################

assign [class="Spotify"] → $ws10
assign [instance="spotify"] → $ws10
assign [class="pomotroid"] → $ws7
# spotify not working 2021-05-31
# assign [class="firefox" title="todoist.com"] → $ws8
assign [instance="calendar.google.com__calendar"] → $ws8
# exec --no-startup-id sleep 30; "$HOME/.local/share/applications/Todoist (WebApp).desktop"
assign [instance="Mail" class="Thunderbird"] → $ws7
# assign [class="kakaotalk.exe"] → $ws9
# assign [class="kakaotalk.exe" window_type="dialog" title="KakaoTalkShadowWnd"]
# assign [class="kakaotalk.exe" window_type="dialog" title="KakaoTalkEdgeWnd"]
