# In-App Popup Windows
################################################################################

for_window [window_role="GtkFileChooserDialog"] resize set width 1600px
for_window [class="firefox" title="About Mozilla Firefox"] floating enable
for_window [class="firefox" title="Picture-in-Picture"] floating enable, \
	border pixel $border_px
# for_window [class="1Password" title=".* 1Password"] floating disable
for_window [class="1Password" title="Keyboard Shortcuts"] floating enable, \
	move position mouse
for_window [class="1Password" title="1Password"] floating enable, \
	resize set width 1px height 1px, \
	sticky enable
	# move position center, \
# for_window [class="1Password" title="1Password"] move position center
# for_window [class="1Password" title="1Password"] move position center
for_window [class="Anki" title="환경 설정"] floating enable
# for_window [window_role="browser" \
# 	title="Sign in with Apple ID — Mozilla Firefox.*"] floating enable
# for_window [class="firefox" window_role="Organizer"] floating enable
# for_window [class="Firefox" title="Kakao Account .*"] floating enable
# for_window [class="firefox" title="본인확인 통신사 선택 — Mozilla Firefox"] \
# 	floating enable
for_window [class="firefox" title="네이버페이 비밀번호 — Mozilla Firefox"] \
	floating enable
# for_window [class="firefox" title="로그인 — Mozilla Firefox"] floating enable
for_window [class="Thunderbird" window_role="Manager|filterlist|Preferences|EventSummaryDialog|EventDialog|addressbookAddWindow"] \
	floating enable
#for_window [class="Thunderbird" instance="Calendar"] \
#	floating enable
for_window [class="Steam" title="Steam - News (.*)|Friends List|KOMOJU|Steam Library Folders"] floating enable
for_window [class="1Password" title="Two-factor authentication"] \
	floating enable
# for_window [class="matplotlib"] floating enable
# vim:ft=conf
