# floating enable (e.g. Float Download Folder / Bookmarks)
# TODO: urgent에 recent 항목있는데 이거 써먹을 수 있을까?  <2022-03-25, Hyunjae Kim> #
# for_window [app_id="firefox" title="Library" urgent="latest"] floating enable

# Others
for_window [app_id="anki"] floating enable
for_window [app_id="anki" title=".* - Anki"] floating disable
for_window [app_id="pcmanfm-qt" title="Copy Files"] floating enable
for_window [app_id="pcmanfm-qt" title="Removable medium is inserted"] floating enable
for_window [app_id="virt-manager" title="Virtual Machine Manager"] floating enable
for_window [app_id="org.kde.digikam" title=".+digiKam"] floating enable
for_window [app_id="org.remmina.Remmina" title="Remmina Remote Desktop Client"] \
	floating enable, border pixel $border_px
	# resize set width 100x height 102px
for_window [app_id="org.kde.dolphin" title="Deleting — Dolphin"] \
	floating enable, border pixel $border_px
for_window [app_id="qdirstat" title="Select Directory"] floating enable

# Firefox
for_window [app_id="firefox" title="About Mozilla Firefox"] floating enable
for_window [app_id="firefox" title="Firefox — Sharing Indicator"] floating enable
for_window [app_id="firefox" title="Picture-in-Picture"] floating enable
#  — : dash가 아님.
for_window [app_id="firefox" title="Page Info — .*"] floating enable, move position center, resize set width 600px height 400px
for_window [app_id="firefox" title="네이버페이 비밀번호 - Mozilla Firefox"] floating enable
for_window [app_id="firefox" title="휴대폰 안심본인인증 - PASS - 통신사 선택 — Mozilla Firefox"] floating enable
for_window [app_id="firefox" title="PAYCO — Mozilla Firefox"] floating enable
# skt 구매확정 윈도우
for_window [app_id="firefox" title="SKT 11번가 — Mozilla Firefox"] floating enable
for_window [app_id="firefox" title="Extension: \(.*"] floating enable
# for_window [app_id="firefox" title="Extension: \(.*uBlock₀ — Logger — Mozilla Firefox"] floating enable
# for_window [app_id="firefox" title="Extension: \(Block Site\).*"] floating enable, resize set height 180px

# Thunderbird
for_window [app_id="thunderbird" title="New Event:.*"] floating enable
for_window [app_id="thunderbird" title="새 이벤트:.*"] floating enable
for_window [app_id="thunderbird" title="Edit Event:.*"] floating enable
for_window [app_id="thunderbird" title="이벤트 편집:.*"] floating enable

for_window [app_id="thunderbird" title="Create New Calendar"] floating enable
for_window [app_id="thunderbird" title="새 캘린더 만들기"] floating enable
for_window [app_id="thunderbird" title="캘린더 편집"] floating enable

for_window [app_id="thunderbird" title="New Task:.*"] floating enable
for_window [app_id="thunderbird" title="새 태스크:.*"] floating enable
for_window [app_id="thunderbird" title="Edit Task:.*"] floating enable
for_window [app_id="thunderbird" title="태스크 편집:.*"] floating enable

for_window [app_id="thunderbird" title=".*개의 미리 알림"] floating enable
for_window [app_id="thunderbird" title="쓰기:.*"] floating enable
for_window [app_id="thunderbird" title="TbSync account manager"] floating enable

#
for_window [app_id="lxqt-policykit-agent" ] floating enable

# GIMP
for_window [app_id="file-pdf-load" ] floating enable
for_window [app_id="file-png" ] floating enable
for_window [app_id="file-jpeg" ] floating enable
for_window [app_id="file-webp" ] floating enable
for_window [app_id="gimp-2.99" title="Image Recovery" ] floating enable

# Kontact
for_window [app_id="org.kde.kontact" title="Configure .* - Kontact"] floating enable

# Libreoffice
for_window [app_id="soffice" title="Text Import - \[.*\]"] floating enable
for_window [app_id="soffice" title="LibreOffice.Document.Recovery"] floating enable
for_window [app_id="soffice" title="Open"] floating enable

# Evolution
for_window [app_id="evolution" title="Task — .*"] floating enable
for_window [app_id="evolution" title="Appointment — .*"] floating enable
