# AUTOSTART CONFIG
################################################################################

#### DE Features

# set program-relauncher.sh "$HOME/.local/bin/program-relauncher.sh"
# exec_always --no-startup-id __program-relauncher.sh __sway-output-setup

# $execi dunst # dunst 실행안해도 자동으로 불러들이는 듯 (2020-12-06)
# KDE 패키지 여럿 설치해서 그런가 dunst 자동 실행 안됨 (2021-11-03)
# dunst는 i3 restart 해도 살아있어서 다시 시작할 필요 없음 (2021-11-03)
exec --no-startup-id dunst

# exec --no-startup-id pcmanfm --daemon-mode
# exec --no-startup-id lxqt-policykit-agent
# exec --no-startup-id clipmenud
# exec_always --no-startup-id clipcatd

# $execi autocutsel -fork
# $execi autocutsel -selection PRIMARY -fork

###
exec_always --no-startup-id brightnessctl --device=asus::kbd_backlight set 3
# exec --no-startup-id gammastep
exec_always --no-startup-id __ime-launcher


# Late Start
#### exec_always --no-startup-id sleep 1; blueman-applet
# exec --no-startup-id sleep 1; QT_FONT_DPI=200 dropbox

# icon size does not match
# exec --no-startup-id alacritty
# exec --no-startup-id /usr/lib/evolution-data-server/evolution-alarm-notify


# exec_always --no-startup-id program-relauncher.sh ulauncher --hide-window
exec_always --no-startup-id __program-relauncher.sh blueman-applet
exec_always --no-startup-id __program-relauncher.sh nm-applet --indicator
exec_always --no-startup-id __program-relauncher.sh albert
# exec_always --no-startup-id program-relauncher.sh firewall-applet "" 2
exec_always --no-startup-id __program-relauncher.sh 1password --silent
exec_always --no-startup-id __program-relauncher.sh kdeconnect-indicator
# exec_always --no-startup-id program-relauncher.sh copyq
# exec_always --no-startup-id __program-relauncher.sh nextcloud --background
exec_always --no-startup-id __program-relauncher.sh syncthing-gtk --minimized
# exec --no-startup-id kdeconnect
exec --no-startup-id spotifyd

# exec --no-startup-id program-relauncher.sh kmail "" 2
exec systemctl --user start spotifyd
exec_always --no-startup-id brightnessctl --device=asus::kbd_backlight set 0


##################
# python 프로그램이라 _program-relauncher 안먹음
exec sleep 2; gammastep-indicator
# exec_always --no-startup-id __program-relauncher.sh gammastep-indicator
