- name: Setup OnlyOffice with flatpak
  hosts: localhost
  become: false
  vars:
    app_id: org.onlyoffice.desktopeditors
    xdg_data_home: "{{ ansible_env.XDG_DATA_HOME | default(ansible_env.HOME + '/.local/share') }}"
  tasks:
    - name: Install {{ app_id }} with flatpak
      community.general.flatpak:
        method: user
        state: present
        remote: flathub
        name:
          - "{{ app_id }}"
    - name: Configure {{ app_id }} flatpak overrides
      copy:
        dest: "{{ xdg_data_home }}/flatpak/overrides/{{ app_id }}"
        # INFO: 기본으로 host 파일을 전부 읽을 수 있게 설정되어 있음. <2025-03-21>
        content: |
          [Context]
          filesystems=!host;home
        mode: '0644'
        backup: false
