- name: Setup Calibre with flatpak
  hosts: localhost
  become: false
  vars:
    app_id: com.calibre_ebook.calibre
    xdg_data_home: "{{ ansible_env.XDG_DATA_HOME | default(ansible_env.HOME + '/.local/share') }}"
  tasks:
    - name: Install {{ app_id }} with flatpak
      community.general.flatpak:
        method: user
        state: present
        remote: flathub
        name:
          - "{{ app_id }}"
    - name: Create Calibre related desktop entries
      copy:
        # dest: "{{ ansible_env.HOME }}/.local/share/applications/{{ item }}"
        dest: "{{ xdg_data_home }}/applications/{{ item }}.desktop"
        content: |
          [Desktop Entry]
          NoDisplay=true
          Exec=:
          Name=This should not be displayed
          Type=Application
        mode: '0600'
        backup: false
      loop:
        - com.calibre_ebook.calibre.ebook-edit
        - com.calibre_ebook.calibre.ebook-viewer
        - com.calibre_ebook.calibre.lrfviewer
