# NOTE: Proprietary in flathub but MIT license in repo <https://github.com/usebruno/bruno>
- name: Setup Bruno with flatpak
  hosts: localhost
  become: false
  vars:
    app_id: com.usebruno.Bruno
    xdg_data_home: "{{ ansible_env.XDG_DATA_HOME | default(ansible_env.HOME + '/.local/share') }}"
  tasks:
    - name: Install {{ app_id }} with flatpak
      community.general.flatpak:
        method: user
        state: present
        remote: flathub
        name:
          - "{{ app_id }}"
    # - name: Check current flatpak overrides
    #   shell: flatpak override --user --show com.usebruno.Bruno
    #   register: current_overrides
    #   changed_when: false
    #   failed_when: false
    # - name: Set flatpak override for Bruno
    #   command: flatpak override --user --nosocket=wayland com.usebruno.Bruno
    #   when: "'sockets=!wayland' not in current_overrides.stdout"
    - name: Configure {{ app_id }} flatpak overrides
      copy:
        dest: "{{ xdg_data_home }}/flatpak/overrides/{{ app_id }}"
        # Use xwayland <2024-12-11>
        content: |
          [Context]
          sockets=!wayland
        mode: '0644'
        backup: false
    - name: Create {{ app_id }} desktop entry
      copy:
        dest: "{{ xdg_data_home }}/applications/{{ app_id }}.desktop"
        content: |
          [Desktop Entry]
          Name=Bruno
          Exec=flatpak run --branch=stable --command=bruno --file-forwarding com.usebruno.Bruno --ozone-platform-hint=x11 @@u %U @@
          Terminal=false
          Type=Application
          Icon=com.usebruno.Bruno
          StartupWMClass=Bruno
          MimeType=x-scheme-handler/bruno;
          Categories=Development;
          X-Flatpak=com.usebruno.Bruno
        mode: '0600'
        backup: false
