- name: Setup default app
  hosts: localhost
  become: false
  tasks:
    - name: Set Okular
      community.general.xdg_mime:
        mime_types:
          - applications/pdf
        handler: org.kde.okular.desktop
    - name: Set GIMP
      community.general.xdg_mime:
        mime_types:
          - image/x-xcf # *.xcf
          - image/vnd.adobe.photoshop # .psd
        handler: org.gimp.GIMP.desktop
