- name: Setup default app
  hosts: localhost
  become: false
  tasks:
    - name: Set Okular
      community.general.xdg_mime:
        mime_types:
          - applications/pdf
        handler: org.kde.okular.desktop
    - name: Set Onlyoffice
      community.general.xdg_mime:
        mime_types:
          - application/vnd.openxmlformats-officedocument.presentationml.presentation
          - application/vnd.openxmlformats-officedocument.presentationml.slide
          - application/vnd.openxmlformats-officedocument.presentationml.slideshow
          - application/vnd.openxmlformats-officedocument.presentationml.template
          - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
          - application/vnd.openxmlformats-officedocument.spreadsheetml.template
          - application/vnd.openxmlformats-officedocument.wordprocessingml.document
          - application/vnd.openxmlformats-officedocument.wordprocessingml.template
        handler: org.onlyoffice.desktopeditors.desktop
    - name: Set LibreOffice
      block:
        - name: Set LibreOffice Writer
          community.general.xdg_mime:
            mime_types:
              - application/vnd.oasis.opendocument.text
              - application/vnd.oasis.opendocument.text-template
              - application/vnd.oasis.opendocument.text-flat-xml
              - application/vnd.oasis.opendocument.text-master
              - application/vnd.oasis.opendocument.text-master-template
              - application/vnd.oasis.opendocument.text-web
            handler: org.libreoffice.LibreOffice.writer.desktop
        - name: Set LibreOffice Calc
          community.general.xdg_mime:
            mime_types:
              - application/vnd.oasis.opendocument.chart
              - application/vnd.oasis.opendocument.chart-template
              - application/vnd.oasis.opendocument.spreadsheet
              - application/vnd.oasis.opendocument.spreadsheet-flat-xml
              - application/vnd.oasis.opendocument.spreadsheet-template
            handler: org.libreoffice.LibreOffice.calc.desktop
        - name: Set LibreOffice Impress
          community.general.xdg_mime:
            mime_types:
              - application/vnd.oasis.opendocument.presentation
              - application/vnd.oasis.opendocument.presentation-template
              - application/vnd.oasis.opendocument.presentation-flat-xml
            handler: org.libreoffice.LibreOffice.impress.desktop
        - name: Set LibreOffice Base
          community.general.xdg_mime:
            mime_types:
              - application/vnd.oasis.opendocument.base
            handler: org.libreoffice.LibreOffice.base.desktop
        - name: Set LibreOffice Draw
          community.general.xdg_mime:
            mime_types:
              - application/vnd.oasis.opendocument.graphics
              - application/vnd.oasis.opendocument.graphics-flat-xml
              - application/vnd.oasis.opendocument.graphics-template
            handler: org.libreoffice.LibreOffice.draw.desktop
        - name: Set LibreOffice Math
          community.general.xdg_mime:
            mime_types:
              - application/vnd.oasis.opendocument.formula
              - application/vnd.oasis.opendocument.formula-template
            handler: org.libreoffice.LibreOffice.math.desktop
    - name: Set GIMP
      community.general.xdg_mime:
        mime_types:
          - image/x-xcf # *.xcf
          - image/vnd.adobe.photoshop # .psd
        handler: org.gimp.GIMP.desktop
