- name: Check if app-com.mitchellh.ghostty.service exists
  command: systemctl --user cat app-com.mitchellh.ghostty.service
  register: ghostty_service_check
  failed_when: false
  changed_when: false
- name: Enable & start ghostty service
  when: [ghostty_service_check.rc == 0]
  systemd:
    name: app-com.mitchellh.ghostty.service
    enabled: true
    state: started
    scope: user
