inode/directory eza --all --links --time-style long-iso --color=always --icons=always --git --mounts --extended --group-directories-first -- %pistol-filename%
text/* bat --style=plain --color=always --paging=never --italic-text=always --wrap=character -- %pistol-filename%
application/javascript bat --style=plain --color=always --paging=never --italic-text=always --wrap=character -- %pistol-filename%
application/postscript bat --style=plain --color=always --paging=never --italic-text=always --wrap=character -- %pistol-filename%
video/* mediainfo -- %pistol-filename%
audio/* mediainfo -- %pistol-filename%
