- name: Set profile picture if accounts-daemon is available
  when:
    - is_home
    - ansible_system == "Linux"
  vars:
    target_user: "{{ ansible_user_id }}"
    image_path: "{{ playbook_dir }}/files/profile.png"
    config_path: "/var/lib/AccountsService/users/{{ target_user }}"
    icon_path: "/var/lib/AccountsService/icons/{{ target_user }}"
  block:
    - name: Check if accounts-daemon service exists
      set_fact:
        is_accounts_daemon: "'accounts-daemon.service' in ansible_facts.services"
    - name: Set profile picture
      when:
        - is_accounts_daemon
      block:
        - name: Copy profile image to icon path
          become: true
          become_user: root
          copy:
            src: "{{ image_path }}"
            dest: "{{ icon_path }}"
            owner: root
            group: root
            mode: '0644'
        - name: Update AccountsService config
          become: true
          become_user: root
          ini_file:
            path: "{{ config_path }}"
            section: User
            option: icon
            value: "{{ icon_path }}"
            create: true
            owner: root
            group: root
            mode: '0600'
