#!/usr/bin/env -S just --justfile

_:
    @just --list

clone:
    mani sync

# mdcat 은 pipe 로 받았을때 처리가 잘 안됨. 2025-09-10

fetch:
    mani run fetch | glow

pull:
    mani run pull | glow

status:
    mani run status | glow
