---
- name: Set audio player
  include_tasks: audio-player.yaml
- name: Set browser
  include_tasks: browser.yaml
- name: Set others
  include_tasks: others.yaml
- name: Remove brave associations
  include_tasks: remove-associations-brave.yaml
- name: Remove chrome associations
  include_tasks: remove-associations-chrome.yaml
- name: Set text editor
  include_tasks: text-editor.yaml
- name: Set video player
  include_tasks: video-player.yaml
