[main]
shell=/usr/bin/env zsh
include=~/.config/foot/themes/gruvbox-dark-tuned.ini
font=Sarasa Fixed K Nerd Font:size=11
# use font's glyphs
box-drawings-uses-font-glyphs=true
pad=3x3 center-when-maximized-and-fullscreen
initial-window-size-chars=80x25
workers=4
term="xterm-256color" # default: foot

[bell]
notify=true

[environment]
BAT_THEME=gruvbox-dark

[key-bindings]
# Reserved for tmux split below.
show-urls-launch=none

[text-bindings]
# tmux prefix: Alt-e (ESC e)
\x1be\x25=Control+Shift+o
\x1be\x22=Control+Shift+e
\x1be\x1b[D=Control+Shift+bracketleft Control+Alt+Left
\x1beo=Control+Shift+bracketright
\x1be\x1b[A=Control+Alt+Up
\x1be\x1b[B=Control+Alt+Down
\x1be\x1b[C=Control+Alt+Right
\x1bez=Control+Shift+Return
\x1bec=Control+Shift+t
\x1ben=Control+Tab Control+Page_Down Control+Shift+Left
\x1bep=Control+Shift+Tab Control+Page_Up Control+Shift+Right
\x1be0=Alt+0
\x1be1=Alt+1
\x1be2=Alt+2
\x1be3=Alt+3
\x1be4=Alt+4
\x1be5=Alt+5
\x1be6=Alt+6
\x1be7=Alt+7
\x1be8=Alt+8
