[main]
shell=/usr/bin/env zsh
include=~/.config/foot/themes/gruvbox-dark.ini
font=Sarasa Fixed K Nerd Font:size=11
# use font's glyphs
box-drawings-uses-font-glyphs=true
pad=3x3 center-when-maximized-and-fullscreen
initial-window-size-chars=80x25
workers=4

[bell]
notify=true
