if (( ! $+commands[podman] )); then
    return
fi

# alias pm='podman'
# alias pmh='podman --help | bat'
# alias pmc='podman container'
# alias pmcl='podman container ls'
# alias pmi='podman image'
# alias pmil='podman image ls'
# alias pmn='podman network'
# alias pmnl='podman network ls'
# alias pmv='podman volume'
# alias pmvl='podman volume ls'
# alias pmK='podman kill'
# alias pmst='podman stats'
# alias pmx='podman run'

# alias sp='sudo podman'
# alias sph='sudo podman --help | bat'
# alias spc='sudo podman container'
# alias spcl='sudo podman container ls'
# alias spi='sudo podman image'
# alias spil='sudo podman image ls'
# alias spn='sudo podman network'
# alias spnl='sudo podman network ls'
# alias spv='sudo podman volume'
# alias spvl='sudo podman volume ls'
# alias spK='sudo podman kill'
# alias spst='sudo podman stats'
# alias spx='sudo podman run'
