# Base24: my-rose-pine
# Scheme by Original by [rose-pine](https://github.com/rose-pine), Ported by [hnjae](https://github.com/hnjae)

[colors]
foreground = "#e0def4"
background = "#191724"
selection_bg = "#e0def4"
selection_fg = "#191724"
cursor_bg = "#e0def4"
cursor_border = "#e0def4"
cursor_fg = "#191724"


ansi = [
  "#1f1d2e",
  "#eb6f92",
  "#31748f",
  "#f6c177",
  "#9ccfd8",
  "#c4a7e7",
  "#ebbcba",
  "#e0def4",
]

brights = [
  "#908caa",
  "#eb6f92",
  "#31748f",
  "#f6c177",
  "#9ccfd8",
  "#c4a7e7",
  "#ebbcba",
  "#e0def4",
]

# vi:ft=toml
