# Base24: my-gruvbox-light
# Scheme by hnjae (https://github.com/hnjae), morhetz (https://github.com/morhetz/gruvbox)

[colors]
foreground = "#3c3836"
background = "#fbf1c7"
selection_bg = "#3c3836"
selection_fg = "#fbf1c7"
cursor_bg = "#3c3836"
cursor_border = "#3c3836"
cursor_fg = "#fbf1c7"


ansi = [
  "#ebdbb2",
  "#9d0006",
  "#79740e",
  "#d65d0e",
  "#076678",
  "#8f3f71",
  "#427b58",
  "#3c3836",
]

brights = [
  "#928374",
  "#cc241d",
  "#98971a",
  "#d79921",
  "#458588",
  "#b16286",
  "#689d6a",
  "#7c6f64",
]

# vi:ft=toml
