- name: Configure localhost user environment
  hosts: localhost
  connection: local
  become: false
  roles:
    - gather_facts
    - various
    - role: default_app
      when: is_desktop
    - role: systemd_user_services
      when:
        - ansible_system == "Linux"
        - ansible_service_mgr == "systemd"
