# NOTE:
#   - following version 0.1.1 of base24 <2025-07-28>
#   - <https://github.com/tinted-theming/base24/blob/main/styling.md>
#
# Base24 my-kanagawa-wave - alacritty color config
# Scheme by Original by rebelot (https://github.com/rebelot/kanagawa.nvim), Ported by hnjae (https://github.com/hnjae)
# vi:ft=toml

# COLORFGBG = if (config.base-home.base24.variant == "light") then "0;15" else "15;0";
# [env]
# COLORFGBG = "${COLORFGBG}"

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1f1f28'
foreground = '0xdcd7ba'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1f1f28'
cursor = '0xdcd7ba'

[colors.normal]
black = '0x1f1f28'
red = '0xc34043'
green = '0x76946a'
yellow = '0xc0a36e'
blue = '0x7e9cd8'
magenta = '0x957fb8'
cyan = '0x6a9589'
white = '0xdcd7ba'

# Bright colors
[colors.bright]
black = '0x727169'
red = '0xe46876'
green = '0x98bb6c'
yellow = '0xe6c384'
blue = '0x7fb4ca'
magenta = '0x938aa9'
cyan = '0x7aa89f'
white = '0x7aa89f'

[[colors.indexed_colors]]
index = 16
color = "0xffa066"

[[colors.indexed_colors]]
index = 17
color = "0x43242b"

[[colors.indexed_colors]]
index = 18
color = "0x2a2a37"

[[colors.indexed_colors]]
index = 19
color = "0x223249"

[[colors.indexed_colors]]
index = 20
color = "0xc8c093"

[[colors.indexed_colors]]
index = 21
color = "0xdcd7ba"
