# [terminal.shell]
# program = "tmux"

[general]
import = [
  "~/.config/alacritty/base16.toml",
  "~/.config/alacritty/keybindings.toml",
]

[font]
size = 11.0
builtin_box_drawing = true #

[font.normal]
family = "Monospace"
style = "Regular"

[font.offset]
y = 0

[font.glyph_offset]
y = 0

# [font.bold]
# family = "MesloLGM Nerd Font"
# style = "Bold"
#
# [font.bold_italic]
# family = "MesloLGM Nerd Font"
# style = "Bold Italic"
#
# [font.italic]
# family = "MesloLGM Nerd Font"
# style = "Italic"


[window.padding]
x = 4
y = 4

[window]
dynamic_padding = false
decorations = "full"
dynamic_title = true
blur = true

[window.dimensions]
columns = 90
lines = 30

[hints]
alphabet = "ntesiroahduflpyw,ckv.xmg"

[env]
TERM = "xterm-256color" # To use 256 color on tmux
