# Base24 my-gruvbox-light - alacritty color config
# Scheme by hnjae (https://github.com/hnjae), morhetz (https://github.com/morhetz/gruvbox)
# vi:ft=toml

# COLORFGBG = if (config.base-home.base24.variant == "light") then "0;15" else "15;0";
# [env]
# COLORFGBG = "${COLORFGBG}"

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xfbf1c7'
foreground = '0x3c3836'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xfbf1c7'
cursor = '0x3c3836'

[colors.normal]
black = '0xebdbb2'
red = '0x9d0006'
green = '0x79740e'
yellow = '0xb57614'
blue = '0x076678'
magenta = '0x8f3f71'
cyan = '0x427b58'
white = '0x3c3836'

# Bright colors
[colors.bright]
black = '0x928374'
red = '0xcc241d'
green = '0x98971a'
yellow = '0xd79921'
blue = '0x458588'
magenta = '0xb16286'
cyan = '0x689d6a'
white = '0x7c6f64'

[[colors.indexed_colors]]
index = 16
color = "0xd65d0e"

[[colors.indexed_colors]]
index = 17
color = "0x772529"

[[colors.indexed_colors]]
index = 18
color = "0xebdbb2"

[[colors.indexed_colors]]
index = 19
color = "0x928374"

[[colors.indexed_colors]]
index = 20
color = "0x7c6f64"

[[colors.indexed_colors]]
index = 21
color = "0x3c3836"
