# Base24 my-kanagawa-dragon - alacritty color config
# Scheme by rebelot
# vi:ft=toml

# COLORFGBG = if (config.base-home.base24.variant == "light") then "0;15" else "15;0";
# [env]
# COLORFGBG = "${COLORFGBG}"

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x181616'
foreground = '0xc5c9c5'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x181616'
cursor = '0xc5c9c5'

[colors.normal]
black = '0x0d0c0c'
red = '0xc4746e'
green = '0x8a9a7b'
yellow = '0xff9e3b'
blue = '0x8ba4b0'
magenta = '0xa292a3'
cyan = '0x8ea4a2'
white = '0xc8c093'

# Bright colors
[colors.bright]
black = '0xa6a69c'
red = '0xe46876'
green = '0x87a987'
yellow = '0xe6c384'
blue = '0x7fb4ca'
magenta = '0x938aa9'
cyan = '0x7aa89f'
white = '0xdcd7ba'

[[colors.indexed_colors]]
index = 16
color = "0xc4b28a"

[[colors.indexed_colors]]
index = 17
color = "0x43242b"

[[colors.indexed_colors]]
index = 18
color = "0x0d0c0c"

[[colors.indexed_colors]]
index = 19
color = "0xa6a69c"

[[colors.indexed_colors]]
index = 20
color = "0x7a8382"

[[colors.indexed_colors]]
index = 21
color = "0xc8c093"
