# Base24 my-selenized-light - alacritty color config
# Scheme by hnjae (https://github.com/hnjae), jan-warchol (https://github.com/jan-warchol/selenized)
# vi:ft=toml

# COLORFGBG = if (config.base-home.base24.variant == "light") then "0;15" else "15;0";
# [env]
# COLORFGBG = "${COLORFGBG}"

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xfbf3db'
foreground = '0x53676d'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xfbf3db'
cursor = '0x53676d'

[colors.normal]
black = '0xece3cc'
red = '0xcc1729'
green = '0x428b00'
yellow = '0xa78300'
blue = '0x006dce'
magenta = '0xc44392'
cyan = '0x00978a'
white = '0x3a4d53'

# Bright colors
[colors.bright]
black = '0x909995'
red = '0xd2212d'
green = '0x489100'
yellow = '0xad8900'
blue = '0x0072d4'
magenta = '0xca4898'
cyan = '0x009c8f'
white = '0x909995'

[[colors.indexed_colors]]
index = 16
color = "0xad8900"

[[colors.indexed_colors]]
index = 17
color = "0xd2212d"

[[colors.indexed_colors]]
index = 18
color = "0xece3cc"

[[colors.indexed_colors]]
index = 19
color = "0x909995"

[[colors.indexed_colors]]
index = 20
color = "0x6f8583"

[[colors.indexed_colors]]
index = 21
color = "0x3a4d53"
