#!/usr/bin/env python3
# 다음 코드를 수정하여 작성: https://gist.github.com/artu-hnrq/bfe1df326b3ac70287961d8b54e0e904

import configparser
import os
import shutil
import sys
from pathlib import Path

username = os.getlogin()
script_dir = Path(__file__).parent
image_path = script_dir.joinpath("./profile.png")
config_path = Path(f"/var/lib/AccountsService/users/{username}")
icon_path = Path(f"/var/lib/AccountsService/icons/{username}")


def update_config():
    print("Updating config", file=sys.stderr)

    cfg = configparser.ConfigParser()
    _ = cfg.read(config_path)
    cfg["User"]["Icon"] = str(icon_path)

    with config_path.open("w") as accounts_service:
        cfg.write(accounts_service)


def update_icon():
    print("Copying icon to its path", file=sys.stderr)
    _ = shutil.copy(image_path, icon_path)
    icon_path.chmod(0o644)
    os.chown(icon_path, 0, 0)


def check_cond():
    if os.geteuid() != 0:
        msg = "This action requires root privileges"
        raise PermissionError(msg)

    if not image_path.exists():
        msg = f"{image_path} does not exists"
        raise FileNotFoundError(msg)

    return True


def main():
    _ = check_cond()
    update_icon()
    update_config()


if __name__ == "__main__":
    main()
