#:schema https://cdn.jsdelivr.net/gh/crate-ci/typos@master/config.schema.json

[default]
locale = "en-us"

[files]
extend-exclude = ["*.snippets"]

[default.extend-identifiers]
GpWhisperEnew = "GpWhisperEnew"

[default.extend-words]
# In vim context:
nore = "nore"
fo = "fo"

[type.lua.extend-words]
"noice" = "noice"     # plugin name
"spectre" = "spectre" # plugin name

[type.json.extend-identifiers]
# In Unity context:
MonoBehaviour = "MonoBehaviour"
StateMachineBehaviour = "StateMachineBehaviour"
NetworkBehaviour = "NetworkBehaviour"

[type.json.extend-words]
# Prefix in snippets
FUL = "FUL"
afe = "afe"
ba = "ba"
caf = "caf"
cntxt = "cntxt"
contxt = "contxt"
definit = "definit"
exten = "exten"
fle = "fle"
fo = "fo"
fof = "fof"
forin = "forin"
forr = "forr"
fpr = "fpr"
fre = "fre"
gti = "gti"
ontext = "ontext"
parsef = "parsef"
pn = "pn"
ser = "ser"
stip = "stip"
whe = "whe"
selectd = "selectd"
processs = "processs"

# LaTeX
multline = "multline"

# Proper Noun
Neuton = "Neuton"
noice = "noice"
AKS = "AKS"       # Azurerm Kubernetes Cluster

# Unreal Frameworks
UE = "UE"

# Relm4 Frameworks
relm = "relm"

# Cobol
cpy = "cpy"

[type.vimscript.extend-identifiers]
shPosnParm = "shPosnParm"

[type.vimscript.extend-words]
ot = "ot"
