[default]
extend-ignore-re = [
  "\\bmis-typed\\b",
]

[default.extend-identifiers]
GpWhisperEnew = "GpWhisperEnew"

[default.extend-words]
# In Vim Context:
nore = "nore"

# Prefix in snippets
FUL = "FUL"
afe = "afe"
ba = "ba"
caf = "caf"
cntxt = "cntxt"
contxt = "contxt"
definit = "definit"
exten = "exten"
fle = "fle"
fo = "fo"
fof = "fof"
forin = "forin"
forr = "forr"
fpr = "fpr"
fre = "fre"
gti = "gti"
ontext = "ontext"
parsef = "parsef"
pn = "pn"
processs = "processs"
selectd = "selectd"
ser = "ser"
stip = "stip"
whe = "whe"

# LaTeX
multline = "multline"

# Proper Noun
Neuton = "Neuton"
noice = "noice"
AKS = "AKS"     # Azurerm Kubernetes Cluster

# Unreal Frameworks
UE = "UE"

# Relm4 Frameworks
relm = "relm"

# Cobol
cpy = "cpy"

[type.vimscript.extend-identifiers]
shPosnParm = "shPosnParm"

[type.vimscript.extend-words]
ot = "ot"
