#!/usr/bin/env -S just --justfile

set fallback

_:
    @just --list

[group('ci')]
lint:
    devenv tasks run nvim:lint

[group('ci')]
check:
    devenv tasks run ci:check

format:
    devenv shell -- treefmt
