#!/usr/bin/env -S just --justfile

set fallback := true

_:
    @just --list

[group('ci')]
format:
    prek run --hook-stage pre-commit --all-files

[group('ci')]
lint:
    fd --type f --extension lua . -X selene --allow-warnings

[group('ci')]
check: lint
    typos
