# Base24: my-kanagawa-dragon
# Scheme by rebelot

[colors]
foreground = "#c5c9c5"
background = "#181616"
selection_bg = "#c5c9c5"
selection_fg = "#181616"
cursor_bg = "#c5c9c5"
cursor_border = "#c5c9c5"
cursor_fg = "#181616"


ansi = [
  "#0d0c0c",
  "#c4746e",
  "#8a9a7b",
  "#c4b28a",
  "#8ba4b0",
  "#a292a3",
  "#8ea4a2",
  "#c8c093",
]

brights = [
  "#a6a69c",
  "#e46876",
  "#87a987",
  "#e6c384",
  "#7fb4ca",
  "#938aa9",
  "#7aa89f",
  "#dcd7ba",
]

# vi:ft=toml
