# i3-autostart-fast
################################################################################

exec_always --no-startup-id gsettings set org.gnome.desktop.interface scaling-factor 2
exec_always --no-startup-id gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gdk/WindowScalingFactor': <2>}"
