# bindsym $mod+Shift+c reload, $execi "notify-send i3 reloaded"
# bindsym $mod+Shift+c $execi update-i3-config.sh, reload, $execi "notify-send i3 reloaded"
# bindsym $mod+Shift+r $execi update-i3-config.sh, restart, $execi "notify-send i3 restarted"
#
bindsym $mod+Shift+c $execi __i3-update.sh reload
bindsym $mod+Shift+r $execi __i3-update.sh restart
