#
# i3 autostart
#

# exec_always --no-startup-id \
# 	setxkbmap -layout us -variant colemak_dh_matrix -option altwin:swap_alt_win

# Lockscreen
exec --no-startup-id xss-lock -n /usr/lib/xsecurelock/dimmer -l -- xsecurelock
# NOTE: picom 이랑 xrandr 이랑 붙어 있으면 화면 이상하게 뜸. 2020-11-17
exec --no-startup-id picom --experimental-backends --daemon

exec_always --no-startup-id $HOME/.config/polybar/launch.sh
exec_always --no-startup-id feh --bg-fill $HOME/.local/share/wallpaper.jpg

# == Legacy X Server Setting Code (Disabled) ==
# nature scroll & lefthanded mode
# do not use xinput because xinput tool had issue (different behavior for different program)
# $execi_always xinput set-prop "PixArt HP USB Optical Mouse" "libinput Natural Scrolling Enabled" 1
# $execi_always xinput set-prop "PixArt HP USB Optical Mouse" "libinput Left Handed Enabled" 1
# $execi_always setxkbmap -option altwin:swap_alt_win
# exec_always --no-startup-id xrandr --output DisplayPort-1 --scale-from 4512x2538
# exec xrandr --output DisplayPort-1 --scale 1.22x1.22 (2/ 1.75 = 1.14 (if you want 1.75%))
# MEMO: 96.55 DPI for 27inch monitor (x1.702) 2256x1269
# MEMO: 96.38 DPI for 24inch monitor 2016x1134
# MEMO: 97.03 DPI for 14inch monitor 1184x666
# 참고 자료: https://ricostacruz.com/til/fractional-scaling-on-xorg-linux



exec --no-startup-id optimus-manager-qt
# exec --no-startup-id pasystray
