- name: Setup Flatpak remotes and applications
  hosts: localhost
  become: false
  tasks:
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        method: user
        state: present
        flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
        name: flathub
    - name: Install packages
      community.general.flatpak:
        method: user
        state: present
        remote: flathub
        name:
          - com.discordapp.Discord # Proprietary
          - net.ankiweb.Anki
          - com.opera.Opera # for netflix
          # Image
          - org.kde.digikam
          - org.darktable.Darktable
