- name: Setup Telegram with flatpak
  hosts: localhost
  become: false
  vars:
    app_id: org.telegram.desktop # GPL3
    xdg_data_home: "{{ ansible_env.XDG_DATA_HOME | default(ansible_env.HOME + '/.local/share') }}"
  tasks:
    - name: Install {{ app_id }} with flatpak
      community.general.flatpak:
        method: user
        state: present
        remote: flathub
        name:
          - "{{ app_id }}"
    - name: Configure {{ app_id }} flatpak overrides
      copy:
        dest: "{{ xdg_data_home }}/flatpak/overrides/{{ app_id }}"
        content: |
          [Context]
          filesystems=xdg-download
        mode: '0644'
        backup: false
    - name: Create {{ app_id }} desktop entry
      copy:
        dest: "{{ xdg_data_home }}/applications/{{ app_id }}.desktop"
        content: |
          [Desktop Entry]
          Name=Telegram Desktop
          Comment=Run telegram with custom .desktop file
          Exec=flatpak run --branch=stable --command=telegram-desktop --file-forwarding org.telegram.desktop -- @@u %u @@
          Icon=org.telegram.desktop
          Terminal=false
          StartupWMClass=TelegramDesktop
          Type=Application
          Categories=Chat;Network;InstantMessaging;Qt;
          MimeType=x-scheme-handler/tg;
          Keywords=tg;chat;im;messaging;messenger;sms;tdesktop;
          Actions=quit;
          # DBusActivatable=true

          SingleMainWindow=true
          X-GNOME-UsesNotifications=true
          X-GNOME-SingleWindow=true
          X-Flatpak=org.telegram.desktop

          [Desktop Action quit]
          Exec=flatpak run --branch=stable --command=telegram-desktop org.telegram.desktop -quit
          Name=Quit Telegram
          Icon=application-exit
        mode: '0600'
        backup: false
